### ISSUE TITLE
hubert_cn 是哪个模型？

### ISSUE THREAD

**Issue by Rane2021** [ZiqiaoPeng/SyncTalk#109]
我看代码中注释提到了hubert_cn, 请问hubert_cn是哪个模型，能否提供下HF链接

**Comment by husthzy** [comment]
请参考ER-NeRF：hubert-large-ls960-ft

**Comment by Rane2021** [comment]
facebook/hubert-large-ls960-ft 不是英文数据集训练的吗？

**Comment by xiao-keeplearning** [comment]
https://github.com/TencentGameMate/chinese_speech_pretrain 可能是这个

**Comment by ZiqiaoPeng** [comment]
> https://github.com/TencentGameMate/chinese_speech_pretrain 可能是这个

是的
