### ISSUE TITLE
When you will release Preprocessing Code?

### ISSUE THREAD

**Issue by kike-0304** [ZiqiaoPeng/SyncTalk#11]
Good job ! When you will release Preprocessing Code?

**Comment by ZiqiaoPeng** [comment]
The preprocessing code is expected to be updated before the CVPR conference (June 17).

**Comment by AMEERAZAM08** [comment]
Its too late but any way will wait that moment

**Comment by pragnakalpdev30** [comment]
When you will release the Preprocessing Code?

**Comment by ZiqiaoPeng** [comment]
Preprocessing code has been released.
