### ISSUE TITLE
Who needs high-quality lip sync - contact me!

### ISSUE THREAD

**Issue by Chechgroup** [ZiqiaoPeng/SyncTalk#111]
I can do lip sync for any character. I reduced the quality to 10 MB in order to upload video. If you are interested, write to me in telegram: The_best_result

https://github.com/ZiqiaoPeng/SyncTalk/assets/152233811/dcb8586a-13a4-4584-9483-25a08307f20e

https://github.com/ZiqiaoPeng/SyncTalk/assets/152233811/1f044078-6e01-4b72-8898-57419b4d784e

https://github.com/ZiqiaoPeng/SyncTalk/assets/152233811/aeefbd20-33b5-4864-b6bb-9b441b21635b

**Comment by Buiminhly2303** [comment]
how can you generate with high resolution video??

**Comment by Chechgroup** [comment]
> how can you generate with high resolution video??

I can do it. All questions in telegram

**Comment by G-force78** [comment]
good sync but expressions not aligned

**Comment by Chechgroup** [comment]
> good sync but expressions not aligned

thank you, I really haven’t seen perfect lip sync in three years in this field

**Comment by labakirill** [comment]
Scammer
