### ISSUE TITLE
Train error...

### ISSUE THREAD

**Issue by a3131919** [ZiqiaoPeng/SyncTalk#112]
Hello professor @ZiqiaoPeng  and anybody, Could u pls help me talk a look at this error during the Train Process:

I followed all the instructions and get DONE in data Preprocessing until:

python main.py data/rj/rj/ --workspace model/trail_rj -O --iters 60000 --asr_model ave

Error: 

/home/f/anaconda3/envs/synctalk/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 1; Derived = torch::nn::Conv1dImpl]’:
/home/f/anaconda3/envs/synctalk/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:101:5:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 1; Derived = torch::nn::Conv1dImpl]’
/home/f/anaconda3/envs/synctalk/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:33:8:   required from here
/home/f/anaconda3/envs/synctalk/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:105:27: error: cannot convert ‘const torch::enumtype::kFanIn’ to ‘int’
  105 |     init::kaiming_uniform_(
      |     ~~~~~~~~~~~~~~~~~~~~~~^
      |                           |
      |                           const torch::enumtype::kFanIn
  106 |         weight,
      |         ~~~~~~~            
  107 |         /*a=*/std::sqrt(5)); // NOLINT(cppcoreguidelines-avoid-magic-numbers)
      |         ~~~~~~~~~~~~~~~~~~~
In file included from /home/f/anaconda3/envs/synctalk/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:5,
                 from /home/f/anaconda3/envs/synctalk/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:16,
                 from /home/f/anaconda3/envs/synctalk/lib/python3.8/site-packages/torch/include/torch/extension.h:5,
                 from /media/f/SecondSSD/DigitalAvatarsProject/SyncTalk/raymarching/src/bindings.cpp:1:
/home/f/anaconda3/envs/synctalk/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/init.h:99:17: note:   initializing argument 3 of ‘at::Tensor torch::nn::init::kaiming_uniform_(at::Tensor, double, int, int)’
   99 |     FanModeType mode = torch::kFanIn,
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.

![123](https://github.com/ZiqiaoPeng/SyncTalk/assets/131645165/a34ebadf-26e0-40f1-a391-ee28b09c5103)

**Comment by ZiqiaoPeng** [comment]
Please install the appropriate torch and cuda environment for your server.

**Comment by trinhtuanvubk** [comment]
@a3131919 Hi, What time does the data preprocessing take ? it took me more than 2 hours and got error. Could you tell me your resources, I used 24gb gpu 32gb ram.
thank you so much
