### ISSUE TITLE
训练完能自动生成测试视频，但进行推理的时候报错

### ISSUE THREAD

**Issue by Jenkit-Lau** [ZiqiaoPeng/SyncTalk#116]
Traceback (most recent call last):
  File "main.py", line 183, in <module>
    trainer = Trainer('ngp', opt, model, device=device, workspace=opt.workspace, criterion=criterion, fp16=opt.fp16, metrics=metrics, use_checkpoint=opt.ckpt)
  File "/home/jenkit/synctalk/nerf_triplane/utils.py", line 735, in __init__
    self.load_checkpoint()
  File "/home/jenkit/synctalk/nerf_triplane/utils.py", line 1532, in load_checkpoint
    missing_keys, unexpected_keys = self.model.load_state_dict(checkpoint_dict['model'], strict=False)
  File "/home/jenkit/anaconda3/envs/synctalk/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NeRFNetwork:
        size mismatch for eye_att_net.net.0.weight: copying a param with shape torch.Size([16, 36]) from checkpoint, the shape in current model is torch.Size([64, 36]).
        size mismatch for eye_att_net.net.1.weight: copying a param with shape torch.Size([1, 16]) from checkpoint, the shape in current model is torch.Size([7, 64]).
        size mismatch for sigma_net.net.0.weight: copying a param with shape torch.Size([64, 69]) from checkpoint, the shape in current model is torch.Size([64, 75]).
        
     训练完模型后自动推理测试视频能正常生成，但运行推理代码：
     python main.py data/john --workspace  model/trial_john -O --test --asr_model hubert --portrait --aud ./demo/test_hu.npy
     就出现上面的错误。已经试过hubert、deepspeech、ave三种方式训练的模型，推理都是出现同样的错误。

**Comment by G-force78** [comment]
If you trained and processed in FP16 you must test and inference with it too

**Comment by ZiqiaoPeng** [comment]
在训练时使用了“--au45”，在推理时也需要使用。
