### ISSUE TITLE
Head Points Tracker and Bundle Adjustment in the paper

### ISSUE THREAD

**Issue by a-thousand-suns** [ZiqiaoPeng/SyncTalk#12]
Could you share the code about the head pose, I could not get a good result as described in the paper.

**Comment by ZiqiaoPeng** [comment]
The preprocessing code is expected to be updated before the CVPR conference (June 17).

**Comment by a-thousand-suns** [comment]
As in paper: 'we use the Laplacian filter to select the keypoints where the most significant flow changes are located and track the
motion trajectories of these keypoints in the flow sequence.'  Could you explain the implementation details?

**Comment by sachinchandra** [comment]
Is the new preprocessing code live? I see some RAD-nerf based one for face tracking. Is it what you used for your implementation also?
