### ISSUE TITLE
请求评估代码和测试数据

### ISSUE THREAD

**Issue by aidenyzhang** [ZiqiaoPeng/SyncTalk#121]
尊敬的SyncTalk团队，

您好！我拜读了您在CVPR 2024上发表的论文《SyncTalk: The Devil is in the Synchronization for Talking Head Synthesis》，并对您的评估方法表示赞赏。我认为您使用的评估集和方法非常合理，避免了一些其他研究中可能出现的问题（比如命中训练集里的数据）。
![Uploading image.png…]()

为了深入研究和学习，我希望能够获得以下信息：

**评估集**：您在论文中使用的评估集的具体信息。比如，评估数据的数量和filelist
**评估方法**：相关的评估代码，以及如何复现您论文中的对其他方法评估过程。比如，PSNR/SSIM/LPIPS是基于全图还是脸部区域做，是基于所有帧还是抽取了部分帧。

请问是否方便分享这些信息？非常感谢！

祝研究进展顺利！

**Comment by aidenyzhang** [comment]
<img width="1345" alt="image" src="https://github.com/ZiqiaoPeng/SyncTalk/assets/79260603/3ab64cc5-cab5-46ac-aed2-e3212c84fdd1">

**Comment by ZiqiaoPeng** [comment]
已和您进行联系。

**Comment by SoberDanz** [comment]
> 已和您进行联系。

您好，我也对您SyncTalk工作中的评估方法十分感兴趣，是否能分享下在实验中相关的评估代码，以及如何复现论文中的对其他方法评估过程？ 还有就是由于基于GAN方法和基于Nerf方法训练数据的不同方式，您在评估过程中是选取哪些数据集进行训练的呢。  万分感谢！

**Comment by LiuKe3068LikWix** [comment]
> 已和您进行联系。

您好，SyncTalk是一个非常值得follow的工作，我也对您的评估方法（评估集，评估代码等）十分感兴趣，请问是否可以分享相关资料，万分感激！！！

**Comment by 2hiTee** [comment]
> 已和您进行联系。

您好，Synctalk是一个具有创新性的工作，我对您的评估集和评估代码很感兴趣，如果可以的话能否分享相关代码和评估集，十分感谢您的分享，再次感谢您的工作！

**Comment by kobeap** [comment]
您好，Synctalk是一个具有创新性的工作，非常值得follow,我对您的评估集和评估代码很感兴趣，想请问能否分享相关代码和评估集，十分感谢您的分享，再次感谢您的工作！

**Comment by kobeap** [comment]
> 已和您进行联系。

您好，Synctalk是一个具有创新性的工作，非常值得follow,我对您的评估集和评估代码很感兴趣，想请问能否分享相关代码和评估集，十分感谢您的分享，再次感谢您的工作！

**Comment by QwertyLqLq** [comment]
> 已和您进行联系。

同求分享，万分感谢！！

**Comment by kobeap** [comment]
有没有哥们有拿到作者的评估代码的？可以分享一下嘛？

**Comment by adadadawn** [comment]
有没有哥们拿到作者的评估代码,希望可以分享一下,谢谢!

**Comment by piwawa** [comment]
希望作者直接开源这部分代码

**Comment by yangziheng110** [comment]
哪位哥们拿到了作者的评估代码，能不能分享一下，感谢！
