### ISSUE TITLE
关于torch依赖冲突

### ISSUE THREAD

**Issue by reputationMK** [ZiqiaoPeng/SyncTalk#123]
xformers要求torch==2.3.0,提供的torch==1.12.1,而facenet_pytorch要求torch==2.2.2,请问这个问题是如何解决呢？十分感谢！

**Comment by ZiqiaoPeng** [comment]
本代码没有对xformers的要求，请按照readme重新配置环境。

**Comment by reputationMK** [comment]
收到，感谢回复！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月15日 23:31 |
| 收件人 | ***@***.***> |
| 抄送至 | Ma ***@***.***>***@***.***> |
| 主题 | Re: [ZiqiaoPeng/SyncTalk] 关于torch依赖冲突 (Issue #123) |

Closed #123 as completed.
