### ISSUE TITLE
process.py 报错 list index out of range

### ISSUE THREAD

**Issue by zhouzhenneng** [ZiqiaoPeng/SyncTalk#132]
目前我正在预处理一个五分钟的视频，视频中女生的长头发，垂在面部两侧，预处理命令如下：
CUDA_VISIBLE_DEVICES=3 python data_utils/process.py  /root/share/SyncTalk/train/data/yangmengyan_stand_jacket_head/yangmengyan_stand_jacket_head.mp4  --asr hubert
执行过程中报错：
face tracking params saved
[INFO] ===== finished face tracking =====
[INFO] ===== extract flow =====
num data:  7897
load done
  0%|                                                                           | 0/7897 [00:00<?, ?it/s]/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
100%|████████████████████████████████████████████████████████████████| 7897/7897 [04:34<00:00, 28.81it/s]
bundle adjustment params saved
[INFO] ===== extract blendshape =====
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1715968442.669229  150331 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
W0000 00:00:1715968442.669731  150331 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
npy file not exists: yangmengyan_stand_jacket
fps: 24.99683464168144
frame_count: 7897
total: 7897
videoPath:yangmengyan_stand_jacket.mp4 fps:24.99683464168144,k
  0%|                                                                           | 0/7897 [00:00<?, ?it/s]Traceback (most recent call last):
  File "data_utils/blendshape_capture/main.py", line 88, in <module>
    infer_bs(args.path)
  File "data_utils/blendshape_capture/main.py", line 65, in infer_bs
    result.face_blendshapes[0]]
IndexError: list index out of range
  0%|                                                                           | 0/7897 [00:00<?, ?it/s]
[INFO] ===== save transforms =====
[INFO] ===== finished saving transforms =====

当我继续执行训练命令是，会继续报错：
filenotfounderror: [errno 2] no such file or directory: '/root/share/synctalk/train/data/yangmengyan_stand_jacket_head/bs.npy'

我查看了相关的代码，问题好像出现在没有能正确的识别面部，我查看了data/face_mask, 选取一张如下：
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/61978338/5cf23a3b-e0b0-4563-8161-38e9426e86bf)
<img width="1167" alt="meishi_20240518_an1KEMjNRf" src="https://github.com/ZiqiaoPeng/SyncTalk/assets/61978338/461531ad-5f99-4804-bf7e-b49a886d8484">

是不是长头发影响了面部识别，synctalk支持长头发训练推理吗

**Comment by zhouzhenneng** [comment]
train/data/目录下不能有多个mp4文件，只存放<ID>_head.mp4

**Comment by HardikJain02** [comment]
same error, i changed data_utils/blendshape_capture/main.py

new code ignores where no face is detected. and generates bs.npy

```
# -*-coding:utf-8-*-
import argparse
import os
import random
import numpy as np
import cv2
import glob
from mediapipe import solutions
from mediapipe.framework.formats import landmark_pb2
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from scipy.signal import savgol_filter
import onnxruntime as ort
from collections import OrderedDict
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
from tqdm import tqdm

def infer_bs(root_path):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    base_options = python.BaseOptions(model_asset_path="./data_utils/blendshape_capture/face_landmarker.task")
    options = vision.FaceLandmarkerOptions(base_options=base_options,
                                           output_face_blendshapes=True,
                                           output_facial_transformation_matrixes=True,
                                           num_faces=1)
    detector = vision.FaceLandmarker.create_from_options(options)

    for i in os.listdir(root_path):
        if i.endswith(".mp4"):
            mp4_path = os.path.join(root_path, i)
            npy_path = os.path.join(root_path, "bs.npy")
            if os.path.exists(npy_path):
                print("npy file exists:", i.split(".")[0])
                continue
            else:
                print("npy file not exists:", i.split(".")[0])
                image_path = os.path.join(root_path, "img/temp.png")
                os.makedirs(os.path.join(root_path, 'img/'), exist_ok=True)
                cap = cv2.VideoCapture(mp4_path)
                fps = cap.get(cv2.CAP_PROP_FPS)
                frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
                print("fps:", fps)
                print("frame_count:", frame_count)
                k = 0
                total = frame_count
                bs = np.zeros((int(total), 52), dtype=np.float32)
                print("total:", total)
                print("videoPath:{} fps:{},k".format(mp4_path.split('/')[-1], fps))
                pbar = tqdm(total=int(total))
                while (cap.isOpened()):
                    ret, frame = cap.read()
                    if ret:
                        cv2.imwrite(image_path, frame)
                        image = mp.Image.create_from_file(image_path)
                        result = detector.detect(image)
                        if result.face_blendshapes:
                            face_blendshapes_scores = [face_blendshapes_category.score for face_blendshapes_category in result.face_blendshapes[0]]
                            blendshape_coef = np.array(face_blendshapes_scores)[1:]
                            blendshape_coef = np.append(blendshape_coef, 0)
                            bs[k] = blendshape_coef
                        else:
                            print("No face blendshapes detected in frame:", k)
                            continue
                        pbar.update(1)
                        k += 1
                    else:
                        break
                cap.release()
                pbar.close()
                output = np.zeros((bs.shape[0], bs.shape[1]))
                for j in range(bs.shape[1]):
                    output[:, j] = savgol_filter(bs[:, j], 5, 3)
                np.save(npy_path, output)
                print(np.shape(output))

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--path", type=str, help="idname of target person")
    args = parser.parse_args()
    infer_bs(args.path)

```
