### ISSUE TITLE
indexerror问题，请问应该如何解决？

### ISSUE THREAD

**Issue by reputationMK** [ZiqiaoPeng/SyncTalk#134]
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/74528503/08c95f11-0c1b-4eb1-855c-48548a57d8c6)
test data数据加载出现问题，请问是什么原因呢？

**Comment by Ap1075** [comment]
Hi @reputationMK , how did you solve this?

**Comment by reputationMK** [comment]
Hi@Ap1075, I use 'safe_img_id = f['img_id'] % len(bs)' to ensure that f['img_id'] stays within the valid range before it is used.
