### ISSUE TITLE
环境冲突，facenet-pytorch安装报错，应该如何解决谢谢

### ISSUE THREAD

**Issue by xdujinsiyu** [ZiqiaoPeng/SyncTalk#135]
facenet-pytorch 2.6.0 requires torch<2.3.0,>=2.2.0, but you have torch 1.12.1 which is incompatible.
torchvision 0.17.2 requires torch==2.2.2, but you have torch 1.12.1 which is incompatible.

**Comment by einsqing** [comment]
facenet-pytorch没用

**Comment by xdujinsiyu** [comment]
请问具体应该如何解决呢，查了之后没有找到其他能对应上torch版本的facenet-pytorch，谢谢您的解答

**Comment by einsqing** [comment]
代码中用的地方删除了

**Comment by xdujinsiyu** [comment]
解决了太谢谢您了

**Comment by ZiqiaoPeng** [comment]
已修复。

**Comment by ofdengdeng** [comment]
> 代码中用的地方删除了

你好，请问是把依赖中的facenet-pytorch删除是吗

**Comment by xdujinsiyu** [comment]
对的，应该是把那个部分注释掉就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月26日(周四) 中午11:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZiqiaoPeng/SyncTalk] 环境冲突，facenet-pytorch安装报错，应该如何解决谢谢 (Issue #135)




  
代码中用的地方删除了
  
你好，请问是把依赖中的facenet-pytorch删除是吗

**Comment by ofdengdeng** [comment]
已经重装环境了




Silver&nbsp;lining
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZiqiaoPeng/SyncTalk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月26日(星期四) 中午11:15
***@***.***&gt;;
抄送:&nbsp;"Silver ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZiqiaoPeng/SyncTalk] 环境冲突，facenet-pytorch安装报错，应该如何解决谢谢 (Issue #135)





 对的，应该是把那个部分注释掉就可以了 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年12月26日(周四) 中午11:11 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [ZiqiaoPeng/SyncTalk] 环境冲突，facenet-pytorch安装报错，应该如何解决谢谢 (Issue #135) 
 
 
 
 
    
 代码中用的地方删除了 
    
 你好，请问是把依赖中的facenet-pytorch删除是吗
