### ISSUE TITLE
预处理报错，大佬们指导下

### ISSUE THREAD

**Issue by tgdtu** [ZiqiaoPeng/SyncTalk#138]
Traceback (most recent call last):
  File "D:\face-SyncTalk\SyncTalk\data_utils\process.py", line 477, in <module>
    extract_flow(base_dir, ori_imgs_dir, mask_imgs_dir, flow_dir)
  File "D:\face-SyncTalk\SyncTalk\data_utils\process.py", line 340, in extract_flow
    track_paths = sorted(glob.glob(os.path.join(track_dir, '*.npy')), key=lambda x: int(x.split('/')[-1].split('.')[0]))
  File "D:\face-SyncTalk\SyncTalk\data_utils\process.py", line 340, in <lambda>
    track_paths = sorted(glob.glob(os.path.join(track_dir, '*.npy')), key=lambda x: int(x.split('/')[-1].split('.')[0]))
ValueError: invalid literal for int() with base 10: 'May\\flow_result\\2_0'

**Comment by tgdtu** [comment]
![Uploading 无标题.png…]()

**Comment by tgdtu** [comment]
[INFO] ===== extracted face landmarks =====
[INFO] ===== perform face tracking =====
500 1.5225038528442383 -453.0252990722656
550 1.7606613636016846 -492.8033447265625
600 1.4970917701721191 -533.9745483398438
650 1.487372636795044 -575.901123046875
700 1.59123957157135 -618.2490234375
750 1.4849531650543213 -660.4194946289062
800 1.4859578609466553 -701.6395874023438
850 2.018195867538452 -740.9039306640625
900 3.163132905960083 -775.5362548828125
950 1.4946885108947754 -800.1015014648438
1000 1.5173656940460205 -812.9868774414062
1050 1.6658706665039062 -817.7344360351562
1100 1.623164176940918 -818.6945190429688
1150 1.6650726795196533 -818.4782104492188
1200 1.7394546270370483 -818.0724487304688
1250 1.8062390089035034 -817.671630859375
1300 1.8835933208465576 -817.2886962890625
1350 2.1990818977355957 -816.9223022460938
1400 2.0487935543060303 -816.5673217773438
1450 2.1358213424682617 -816.22412109375
750 1.5193690061569214 -660.6322021484375
face tracking params saved
[INFO] ===== finished face tracking =====
[INFO] ===== extract flow =====
num data:  5450
load done
  0%|                                                                                         | 0/5450 [00:00<?, ?it/s]D:\face-SyncTalk\venv\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
100%|██████████████████████████████████████████████████████████████████████████████| 5450/5450 [13:11<00:00,  6.89it/s]
Traceback (most recent call last):
  File "D:\face-SyncTalk\SyncTalk\data_utils\process.py", line 477, in <module>
    extract_flow(base_dir, ori_imgs_dir, mask_imgs_dir, flow_dir)
  File "D:\face-SyncTalk\SyncTalk\data_utils\process.py", line 340, in extract_flow
    track_paths = sorted(glob.glob(os.path.join(track_dir, '*.npy')), key=lambda x: int(x.split('/')[-1].split('.')[0]))
  File "D:\face-SyncTalk\SyncTalk\data_utils\process.py", line 340, in <lambda>
    track_paths = sorted(glob.glob(os.path.join(track_dir, '*.npy')), key=lambda x: int(x.split('/')[-1].split('.')[0]))
ValueError: invalid literal for int() with base 10: 'May\\flow_result\\2_0'
请按任意键继续. . .

**Comment by ZiqiaoPeng** [comment]
#72

**Comment by tgdtu** [comment]
邮件已收到，谢谢！冶专涂国栋。
