### ISSUE TITLE
how to run inference in my own data

### ISSUE THREAD

**Issue by trinhtuanvubk** [ZiqiaoPeng/SyncTalk#143]
I see May data containing many files. How to run inference in my own video and speech data ?
Thank you so much

**Comment by trinhtuanvubk** [comment]
Im sorry, I see it in the readme, try now

**Comment by newgenai79** [comment]
@trinhtuanvubk 

Di you managed to run using your own data?

**Comment by trinhtuanvubk** [comment]
@newgenai79 Hi, I have run it successfully. Everything you need is a good preprocessing. Input video should be 512x512 and make sure containing face every frames

**Comment by won-bae** [comment]
@newgenai79  Sorry but did you have to train the model with your own data first and then run inference? Or were you able to run inference using pre-trained May checkpoint?

**Comment by newgenai79** [comment]
@won-bae 

I have no idea. I did not tried. Maybe trinhtuanvubk can help as he managed to run it successfully.

**Comment by shounakthevoicing** [comment]
https://github.com/ZiqiaoPeng/SyncTalk/assets/173535969/3ed70be8-10aa-408b-93e7-6909f9f54c55

@trinhtuanvubk I am training for 200k steps total to get video like this. Can you guide me on how to improve the results? Did you use openface or some other features than mediapipe?

**Comment by Deltaidiots** [comment]
@won-bae we you able to run inference with may checkpoints on your own data?
