### ISSUE TITLE
how to process my own video?

### ISSUE THREAD

**Issue by lokvke** [ZiqiaoPeng/SyncTalk#16]
how to process my own video data and train model? the preprocessing code is not releasing yet.

waiting....

**Comment by benchrus** [comment]
The demo result is nice and I want to train with my own video. How can I preprocess data and train model?

**Comment by yaleimeng** [comment]
+1

**Comment by jinqinn** [comment]
@ZiqiaoPeng +1

**Comment by ylz201** [comment]
@ZiqiaoPeng +1

**Comment by vettorazi** [comment]
same

**Comment by jryebread** [comment]
Why was it not released right away? :(

**Comment by WoJiaoFuXiaoYun** [comment]
@ZiqiaoPeng +1

**Comment by pragnakalpdev30** [comment]
+1

**Comment by pragnakalpdev30** [comment]
@ZiqiaoPeng +1

**Comment by ZiqiaoPeng** [comment]
Preprocessing code has been released. Thanks for your patience.
