### ISSUE TITLE
About inference speed.

### ISSUE THREAD

**Issue by Hujiazeng** [ZiqiaoPeng/SyncTalk#17]
How many pictures a second?

**Comment by ZiqiaoPeng** [comment]
`--preload 0`: load from disk (default, slower), about 20FPS.
 `--preload 1`: load to CPU (slightly slower), about 35FPS.
 `--preload 2`: load to GPU (fast), about 50FPS.

**Comment by BakingBrains** [comment]
@ZiqiaoPeng any way to reduce the inference time. Even after setting ```preload 2```, to generate 2300 frames it is taking about 7 min.

**Comment by jinqiupeter** [comment]
> @ZiqiaoPeng any way to reduce the inference time. Even after setting `preload 2`, to generate 600 frames it is taking about 7 min.

You must be using a very old GPU. On my RTX 3090 I got the FPS as @ZiqiaoPeng  mentioned above.

**Comment by BakingBrains** [comment]
@jinqiupeter can you please tell (roughly) what is the inference time you're getting to generate a video of 30 sec.

**Comment by jibril-gudal** [comment]
Same I'm testing on different GPU's like A100, A10 but its still taking 5-7 mins for a 30 second video.
