### ISSUE TITLE
最终全身加背景的视频生成

### ISSUE THREAD

**Issue by Skye2099** [ZiqiaoPeng/SyncTalk#182]
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/56715553/d8c3cf68-1c14-4997-b395-2e1f6cc138bc)
最后这步portrait-sync generator也只是在原portrait视频上做吧，最后全身加背景的最终视频是自己剪辑贴上去吗？

**Comment by Skye2099** [comment]
@ZiqiaoPeng 大佬帮忙确认下

**Comment by debasishaimonk** [comment]
any answer yet??

**Comment by Skye2099** [comment]
> any answer yet??

yes,i have confirmed it.you should cut a new video 512*512 from the original video for training,and paste the inference result back to the original video according to the xy coordinates

**Comment by varunjain99** [comment]
@Skye2099 would this not cause artifacts of the pasted portrait image not being in sync with the rest of the body?

**Comment by iaindian** [comment]
@Skye2099 #and paste the inference result back to the original video according to the xy coordinates

Could you share more details on how to do that ?
