### ISSUE TITLE
脸部出现碎片定格

### ISSUE THREAD

**Issue by zzqwdwd** [ZiqiaoPeng/SyncTalk#194]
想知道怎么解决这种情况，是不是由于我没有将视频裁成512*512导致的还是别的原因

**Comment by zzqwdwd** [comment]
![image](https://github.com/user-attachments/assets/5e920e71-f180-4c3a-ba2c-30d37fc36b67)
视频每一帧都是这个样子

**Comment by 2ezInCode** [comment]
512 * 512 严格的 必须的

**Comment by zzqwdwd** [comment]
> 512 * 512 严格的 必须的

好的，已经解决了，谢谢
