### ISSUE TITLE
inference结果没声音

### ISSUE THREAD

**Issue by lzkgogogo** [ZiqiaoPeng/SyncTalk#21]
The inference results are just like the evalution code and have no audio, anyone has the same problem lime me?

**Comment by ZiqiaoPeng** [comment]
Maybe `ffmpeg` is not working correctly?

**Comment by SoberDanz** [comment]
I've also encountered the same problem. Have you solved your problem now?

**Comment by lzkgogogo** [comment]
> I've also encountered the same problem. Have you solved your problem now?

just conda install ffmpeg

**Comment by karl-tao-zhang** [comment]
apt-get install ffmpeg

then will have  _audio.mp4
