### ISSUE TITLE
推理出来的视频，有时候嘴巴附近变得比较模糊，请问什么原因

### ISSUE THREAD

**Issue by wangyl218** [ZiqiaoPeng/SyncTalk#211]
推理出来的视频，有时候嘴巴附近变得比较模糊，请问什么原因？

![img_v3_02dm_5ef84da3-8810-4b1b-9f54-390bfc05acdg](https://github.com/user-attachments/assets/cdffa7cf-4ec2-46d2-ae89-6b0f5a1defe4)

![img_v3_02dm_41bc10a1-1169-47b6-bfb3-0e6ca8f0f81g](https://github.com/user-attachments/assets/ede08205-79e0-46ff-9916-1a5944470704)

**Comment by varunjain99** [comment]
Were you able to determine the reason?

**Comment by wangyl218** [comment]
> Were you able to determine the reason?

I used hubert or deepspeech as the wav  encoder, it did not  happen anymore
