### ISSUE TITLE
预处理中颈部的填充Cn实现

### ISSUE THREAD

**Issue by Kedreamix** [ZiqiaoPeng/SyncTalk#22]
你好，我想问一下，对于预处理中的颈部的填充是如何填的呢，我借鉴于ER-NeRF的代码来进行修改

我根据论文的思想，取出对应图片的颈部的RGB颜色，然后填充，但是好像效果不一样，就请问一下，大概如何实现的
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/61195303/92a87aab-d0a3-406a-8830-21011cfe6dee)

```
index = np.where(neck_part)
neck_part_image = torso_image[index[0], index[1], :]
neck_part_alpha = torso_alpha[index[0], index[1]]
mean_neck_part_color = np.mean(neck_part_image, axis=0)
mean_neck_part_alpha = np.mean(neck_part_alpha)
torso_image[inpaint_mask] = mean_neck_part_color
torso_alpha[inpaint_mask] = mean_neck_part_alpha
```
![5_inpaint_mask](https://github.com/ZiqiaoPeng/SyncTalk/assets/61195303/73e1ebed-218c-4356-9b68-5618ee8c7f78)

![5](https://github.com/ZiqiaoPeng/SyncTalk/assets/61195303/f1dc1a38-4063-4244-b598-95c15fdc402f)

![5](https://github.com/ZiqiaoPeng/SyncTalk/assets/61195303/79f9a51c-6715-4284-9c69-625636d1f134)

**Comment by ZiqiaoPeng** [comment]
neck_avg_color = np.mean(gt_image[neck_part], axis=0)
        inpaint_neck_colors = top_neck_colors[None].repeat(L, 0)
        alpha_values = np.linspace(1, 0, L).reshape(L, 1, 1) 
        inpaint_neck_colors = inpaint_neck_colors * alpha_values + neck_avg_color * (1 - alpha_values)
        inpaint_neck_colors = inpaint_neck_colors.reshape(-1, 3)
        torso_image[tuple(inpaint_neck_coords.T)] = inpaint_neck_colors
可以参考一下这个流程。

**Comment by Kedreamix** [comment]
好的，非常感谢

**Comment by BakingBrains** [comment]
@Kedreamix can please tell how did you extract the face from the frames.

**Comment by Kedreamix** [comment]
you can use parsing module to extract the face
