### ISSUE TITLE
训练后脖子部分出现背景，请问哪个流程能优化改进

### ISSUE THREAD

**Issue by jukhang** [ZiqiaoPeng/SyncTalk#227]
作者您好，我测试了ER-NERF和SyncTalk，Er-NERF的头部抖动较为明显，SyncTalk效果较好，但是脖子部分出现了背景。

https://github.com/user-attachments/assets/70600050-1b39-4209-ae71-12f8e4129dac

![image](https://github.com/user-attachments/assets/38cd2cf1-27c1-478a-83ad-e84b5a5dedc2)
![image](https://github.com/user-attachments/assets/76a1bc79-959c-4c0f-94f9-59028cab3af6)

是语义分割部分效果不好吗？

**Comment by jukhang** [comment]
![20](https://github.com/user-attachments/assets/592c4c7e-a3fa-46ac-971e-900854b94814)
tor

**Comment by jukhang** [comment]
增加了torso部分训练，双下巴或者背景情况修复了，但是面部出现部分模糊，头部也出现轻微抖动。
![image](https://github.com/user-attachments/assets/d772dd66-2075-482f-8b0d-eaf2c8342758)

https://github.com/user-attachments/assets/830916fb-cd6c-4b4e-aa01-8ec069407238

**Comment by jukhang** [comment]
https://github.com/user-attachments/assets/2c2f8adb-9686-47bb-a79c-e512935c779e

最终训练效果，此 issue 关闭。

**Comment by FBLL** [comment]
你好，铁子，看你后面的视频脸部没有抖动了，脸部抖动是怎么处理的

**Comment by phitrann** [comment]
Hi @jukhang , how did you solve the blurred and head shaking issue? I’m curious about what steps you took to fix it.

**Comment by wangyl218** [comment]
> pantao.2-1.mp4 
> 最终训练效果，此 issue 关闭。

大佬，请问是怎么解决下巴出现背景的问题，我的torso出现这种数据
![Uploading screenshot-20241128-175239.png…]()

**Comment by 08burhan** [comment]
@jukhang hi Jukhang! could you let me know how you were able to resolve the above issues ?
