### ISSUE TITLE
Can not install 3DMM model

### ISSUE THREAD

**Issue by nldhuyen0047** [ZiqiaoPeng/SyncTalk#228]
Hello, thank you for your excellent work.

I downloaded the SyncTalk model to run in local and I have encountered with a problem about the 3DMM model. I could not install this model, and the link attached had error. Could you please send me another version of this model?

Thank you so much.

**Comment by 11898d** [comment]
请问您解决这个问题了吗，我根据链接去下载，指向的是Basel Face Model 2019的链接。

**Comment by 11898d** [comment]
解决了，谢谢。
