### ISSUE TITLE
Why the face rendered incorrectly?

### ISSUE THREAD

**Issue by AdamBear** [ZiqiaoPeng/SyncTalk#23]
generated video:
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/2288870/57839531-1000-479f-87f1-d17aea44d37c)

run log:
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/2288870/bc372d8b-d40b-4eb2-807a-4c84143ec7dc)

**Comment by ZiqiaoPeng** [comment]
`[WARN] No checkpoint found, model randomly initialized.`
Maybe you didn't put [trial_may.zip](https://drive.google.com/file/d/1C2639qi9jvhRygYHwPZDGs8pun3po3W7/view?usp=sharing) in the right place.
