### ISSUE TITLE
how long video length is enough for training to get good result ?

### ISSUE THREAD

**Issue by trangtv57** [ZiqiaoPeng/SyncTalk#233]
Thks for your public,
I want to ask about the length of video require for training for one person to get good result, i try with video length 4 minute, but it's still not has good lip sync. And I don't know your trial_may model is train with multi person or just only May video.
tks you

**Comment by Deltaidiots** [comment]
make sure it has right resolution and fps. also use openface for better results

**Comment by trangtv57** [comment]
ok tks

**Comment by slnrm** [comment]
Hello，Can training be conducted using a video composed of multiple non-continuous video segments?
