### ISSUE TITLE
关于3DMM下载

### ISSUE THREAD

**Issue by 11898d** [ZiqiaoPeng/SyncTalk#235]

**Comment by 11898d** [comment]
我已经下载完成，并找到了对应的文件。谢谢。
![image](https://github.com/user-attachments/assets/01adbaee-0741-42d7-ade1-7746cca510c4)

**Comment by William3242** [comment]
你好，请问凝视如何下载的，我反复检查，但是其中的链接并没有这个文件。

![Image](https://github.com/user-attachments/assets/569a319d-6d63-4b98-9075-871a3825326f)
