### ISSUE TITLE
how to use ave encode？

### ISSUE THREAD

**Issue by kike-0304** [ZiqiaoPeng/SyncTalk#24]
I used ave audio encoder to replace ernerf's audio encoder, and unfortunately I got a worse result.

**Comment by Elysiameik** [comment]
> I used ave audio encoder to replace ernerf's audio encoder, and unfortunately I got a worse result.


I have also been modifying the codes of ernerf and synctalk recently. Can you discuss the related issues with me? My email  is zcygyzytd@gmail.com

**Comment by Elysiameik** [comment]
> I used ave audio encoder to replace ernerf's audio encoder, and unfortunately I got a worse result.


I have also been modifying the codes of ernerf and synctalk recently. Can you please discuss the related issues with me? my email is [zcygyzytd@gmail.com](mailto:zcygyzytd@gmail.com)

**Comment by fengxiang777** [comment]
yeah,I had the same result. My guess is that the ave module is probably less effective than deepspeech. Or maybe I'm not using the ave module correctly.

> I used ave audio encoder to replace ernerf's audio encoder, and unfortunately I got a worse result.

**Comment by kike-0304** [comment]
> 我使用 deepspeech 和 ave 模块中的功能作为输入。结果是，lse-c 在奥巴马视频的测试集上保持不变，并且在其他音频上比 er-nerf 使用的深度语音效果更好。

Great, can you tell me how you use ave?

**Comment by ZiqiaoPeng** [comment]
The code to get ave features has been released.
