### ISSUE TITLE
unstable head result with my own model

### ISSUE THREAD

**Issue by lokvke** [ZiqiaoPeng/SyncTalk#25]
i tried to preprocess my own video data, the bs.npy is generated from EmoTalk project.

**Comment by lokvke** [comment]
https://github.com/ZiqiaoPeng/SyncTalk/assets/95479496/32c95529-8a80-4c9d-b07e-7045c3a4e41f

**Comment by kike-0304** [comment]
> result.mp4

Do you use smooth_path?

**Comment by lokvke** [comment]
@kike-0304 just train with the default config.

**Comment by kike-0304** [comment]
use smooth_path in test may have stable head, and would it be convenient for you to share your data processing code?

**Comment by kike-0304** [comment]
> i tried to preprocess my own video data, the bs.npy is generated from EmoTalk project.

Hello, EmoTalk project does not provide data processing code. How did you generate the bs.np file?

**Comment by lokvke** [comment]
> > i tried to preprocess my own video data, the bs.npy is generated from EmoTalk project.
> 
> Hello, EmoTalk project does not provide data processing code. How did you generate the bs.np file?

https://github.com/psyai-net/EmoTalk_release/blob/5179b27b2fdd1ca27fcbfa6a3264a5ecfd51d524/demo.py#L55

**Comment by kike-0304** [comment]
> > > i tried to preprocess my own video data, the bs.npy is generated from EmoTalk project.
> > 
> > 
> > Hello, EmoTalk project does not provide data processing code. How did you generate the bs.np file?
> 
> https://github.com/psyai-net/EmoTalk_release/blob/5179b27b2fdd1ca27fcbfa6a3264a5ecfd51d524/demo.py#L55
> 
> i don't know if it is right, maybe u can try it.

This is bs.npy obtained from audio, we may need to obtain bs.npy from video frames

**Comment by kike-0304** [comment]
> i tried to preprocess my own video data, the bs.npy is generated from EmoTalk project.

"face_rect": [
61,
0,
384,
468
] means [xmin, ymin, w, h]?

**Comment by lokvke** [comment]
> Hi @lokvke , may I ask which asr_model did you use to train your own video? if it's ave, how did you generate the aud_ave.npy file? thanks!

just use the provided `audio_visual_encoder.pth `

**Comment by jinqiupeter** [comment]
Thanks, I managed to train my own video, though the result is not as good as May's

**Comment by lokvke** [comment]
> Thanks, I managed to train my own video, though the result is not as good as May's

can u show your result here?

**Comment by xiaoxiongzhg** [comment]
> > Thanks, I managed to train my own video, though the result is not as good as May's
> 
> can u show your result here?

bs.npy is closely related to the blinking action. Will your character blink when you replace the bs.npy? In your example video, the characters do not blink.

**Comment by yangzhidao** [comment]
> 结果.mp4

Great, can you tell me how to get ave_npy?

**Comment by jinqiupeter** [comment]
I finally got it working:

https://github.com/ZiqiaoPeng/SyncTalk/assets/12045814/5e9e8a01-6c92-4827-b4aa-1bcb6db2499c

**Comment by jinqiupeter** [comment]
> > > Thanks, I managed to train my own video, though the result is not as good as May's
> > 
> > 
> > can u show your result here?
> 
> bs.npy is closely related to the blinking action. Will your character blink when you replace the bs.npy? In your example video, the characters do not blink.

I updated code to only mask the lower part of the original video, so the characters' upper face remains the same as original video. See my sample above.

**Comment by HenryKang1** [comment]
> > > > Thanks, I managed to train my own video, though the result is not as good as May's
> > > 
> > > 
> > > can u show your result here?
> > 
> > 
> > bs.npy is closely related to the blinking action. Will your character blink when you replace the bs.npy? In your example video, the characters do not blink.
> 
> I updated code to only mask the lower part of the original video, so the characters' upper face remains the same as original video. See my sample above.

Could you share which part do you adjust for this?

**Comment by redstarxz** [comment]
> @jinqiupeter can you share the code adjustments you made for this? looks great.
> 
> hoping someone can create a short guide how to preprocess your own video data.
> 
> edit: welcome to join my discord server to discuss ai avatar stuff and sharing syncTalk tips https://discord.gg/jETUMmUD6h

+1

**Comment by 0918lupus** [comment]
> > i tried to preprocess my own video data, the bs.npy is generated from EmoTalk project.
> 
> "face_rect": [ 61, 0, 384, 468 ] means [xmin, ymin, w, h]?

I also want to know about this.
Does anyone know about it?

**Comment by jinqiupeter** [comment]
> @jinqiupeter can you share the code adjustments you made for this? looks great.
> 
> hoping someone can create a short guide how to preprocess your own video data.
> 
> edit: welcome to join my discord server to discuss ai avatar stuff and sharing syncTalk tips https://discord.gg/jETUMmUD6h

Preprocessing code is mostly the same as ER-NeRF, with too extra parts: 1). bs.npy - this can be generated with EmoTalk.  2). face_mask folder and {i}_face.png in parsing - this can be easily generated by modifying data_utils/face_parsing/test.py, as I put here https://github.com/ZiqiaoPeng/SyncTalk/issues/38#issuecomment-1994401907

**Comment by jinqiupeter** [comment]
ave, the code is already available in nerf_triplane/provider

**Comment by hungho77** [comment]
> > > > i tried to preprocess my own video data, the bs.npy is generated from EmoTalk project.
> > > 
> > > 
> > > Hello, EmoTalk project does not provide data processing code. How did you generate the bs.np file?
> > 
> > 
> > https://github.com/psyai-net/EmoTalk_release/blob/5179b27b2fdd1ca27fcbfa6a3264a5ecfd51d524/demo.py#L55
> > i don't know if it is right, maybe u can try it.
> 
> This is bs.npy obtained from audio, we may need to obtain bs.npy from video frames

hi, i use https://github.com/psyai-net/EmoTalk_release/blob/main/demo.py to create file bs.npy, but the shape output do not match with audio feature shape. Do you meet this problem, please give me advice , thanks.

**Comment by christopherohit** [comment]
> > Thanks, I managed to train my own video, though the result is not as good as May's
> 
> can u show your result here?

Hi can you share preprocessing code ? 
Thank for all your working !!!

**Comment by foxprocn** [comment]
> result.mp4

@lokvke 大佬你好，请问如何训练自己的视频，你的预处理模块是否能提供下，我在自己的视频上进行训练，后续的优化效果模块与您持续共享，可以加我vx:wenfeng071555，期待与您的交流

**Comment by khaidq97** [comment]
Can you share your preprocess 

> > @jinqiupeter can you share the code adjustments you made for this? looks great.
> > hoping someone can create a short guide how to preprocess your own video data.
> > edit: welcome to join my discord server to discuss ai avatar stuff and sharing syncTalk tips https://discord.gg/jETUMmUD6h
> 
> Preprocessing code is mostly the same as ER-NeRF

Can you share your preprocess code ?

**Comment by khaidq97** [comment]
> I finally got it working:
> 
>  kh_kr.mp4

Look great !! Can your share your preprocess and code

**Comment by G-force78** [comment]
> > @jinqiupeter can you share the code adjustments you made for this? looks great.
> > hoping someone can create a short guide how to preprocess your own video data.
> > edit: welcome to join my discord server to discuss ai avatar stuff and sharing syncTalk tips https://discord.gg/jETUMmUD6h
> 
> Preprocessing code is mostly the same as ER-NeRF

Amazing result. What differences?
