### ISSUE TITLE
size mismatch for sigma_net.net.0.weight: copying a param with shape torch.Size([64, 75]) from checkpoint, the shape in current 

### ISSUE THREAD

**Issue by c1a1o1** [ZiqiaoPeng/SyncTalk#29]
D:\anaconda3\python.exe D:\work\SyncTalk\main.py 
Namespace(path='data/May', O=False, test=False, test_train=False, data_range=[0, -1], workspace='model/trial_may', seed=0, iters=200000, lr=0.01, lr_net=0.001, ckpt='latest', num_rays=65536, cuda_ray=True, max_steps=16, num_steps=16, upsample_steps=0, update_extra_interval=16, max_ray_batch=4096, warmup_step=10000, amb_aud_loss=1, amb_eye_loss=1, unc_loss=1, lambda_amb=0.1, pyramid_loss=0, fp16=False, bg_img='', fbg=False, exp_eye=False, fix_eye=-1, smooth_eye=False, bs_area='upper', torso_shrink=0.8, color_space='srgb', preload=0, bound=1, scale=4, offset=[0, 0, 0], dt_gamma=0.00390625, min_near=0.05, density_thresh=10, density_thresh_torso=0.01, patch_size=1, init_lips=False, finetune_lips=False, smooth_lips=False, torso=False, head_ckpt='', gui=False, W=450, H=450, radius=3.35, fovy=21.24, max_spp=1, att=2, aud='demo/test.wav', emb=False, portrait=False, ind_dim=4, ind_num=20000, ind_dim_torso=8, amb_dim=2, part=False, part2=False, train_camera=False, smooth_path=False, smooth_path_window=7, asr=False, asr_wav='', asr_play=False, asr_model='ave', asr_save_feats=False, fps=50, l=10, m=50, r=10)
[INFO] load 5520 train frames.
[INFO] load demo/test.wav aud_features: torch.Size([331, 1, 512])
Loading train data: 100%|██████████| 5520/5520 [00:02<00:00, 2019.28it/s]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
D:\anaconda3\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\anaconda3\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: D:\anaconda3\lib\site-packages\lpips\weights\v0.1\alex.pth
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
D:\anaconda3\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\anaconda3\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: D:\anaconda3\lib\site-packages\lpips\weights\v0.1\alex.pth
[INFO] Trainer: ngp | 2024-03-10_11-51-37 | cuda | fp32 | model/trial_may
[INFO] #parameters: 767717
[INFO] Loading latest checkpoint ...
[INFO] Latest checkpoint is model/trial_may\checkpoints\ngp_ep0019.pth
Traceback (most recent call last):
  File "D:\work\SyncTalk\main.py", line 237, in <module>
    trainer = Trainer('ngp', opt, model, device=device, workspace=opt.workspace, optimizer=optimizer, criterion=criterion, ema_decay=0.95, fp16=opt.fp16, lr_scheduler=scheduler, scheduler_update_every_step=True, metrics=metrics, use_checkpoint=opt.ckpt, eval_interval=eval_interval)
  File "D:\work\SyncTalk\nerf_triplane\utils.py", line 735, in __init__
    self.load_checkpoint()
  File "D:\work\SyncTalk\nerf_triplane\utils.py", line 1532, in load_checkpoint
    missing_keys, unexpected_keys = self.model.load_state_dict(checkpoint_dict['model'], strict=False)
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NeRFNetwork:
	size mismatch for sigma_net.net.0.weight: copying a param with shape torch.Size([64, 75]) from checkpoint, the shape in current model is torch.Size([64, 68]).

Process finished with exit code 1

**Comment by ZiqiaoPeng** [comment]
You can try the latest code.
