### ISSUE TITLE
--bg_img doesn't work when using --portrait

### ISSUE THREAD

**Issue by lokvke** [ZiqiaoPeng/SyncTalk#32]

**Comment by CatherineZhou** [comment]
我也遇到同样问题，readme中提到““portrait” signifies pasting the generated face back onto the original image”， 但是，用“python main.py data/May --workspace model/trial_may -O --test --test_train --asr_model ave --portrait --aud ./demo/test.wav ”生成result文件没有带下半身，只有大头贴。
