### ISSUE TITLE
 Preprocessing Code

### ISSUE THREAD

**Issue by SoberDanz** [ZiqiaoPeng/SyncTalk#33]
Good Job!
When will the preprocessed code be released？？

**Comment by jinqinn** [comment]
+1

**Comment by vettorazi** [comment]
+1

**Comment by lyq1152227095** [comment]
根据ad-nerf，ead-nerf，还有作者自己的emotalk，可以得到数据预处理的代码

**Comment by einsqing** [comment]
> 根据ad-nerf，ead-nerf，还有作者自己的emotalk，可以得到数据预处理的代码

兄弟麻烦分享一下

**Comment by jiangguangan** [comment]
> 根据ad-nerf，ead-nerf，还有作者自己的emotalk，可以得到数据预处理的代码

兄弟我也需要分享一下

**Comment by lyq1152227095** [comment]
https://github.com/ashawkey/RAD-NeRF?tab=readme-ov-file，这个git的Pre-processing Custom Training Video，有一部分数据生成，作者的数据里有个bs.npy，52维的数据，这个我不确定使用的是什么，我用emotalk构建了52维的输出，但是这个是针对音频提取的人脸矩阵，感觉和作者的表述基于人脸的还不太一样，感兴趣加微信V+：lyq176599，我拉个群大家讨论，我也有好多地方不太确定，我复现的效果不是很好

**Comment by ZiqiaoPeng** [comment]
Preprocessing code has been released. Thanks for your patience.
