### ISSUE TITLE
请问Portrait-Sync Generator这部分模块在哪个部分？

### ISSUE THREAD

**Issue by zckcola** [ZiqiaoPeng/SyncTalk#36]

**Comment by ZiqiaoPeng** [comment]
--portrait
是该模块的调用方式，具体实现可以参考[utils.py](https://github.com/ZiqiaoPeng/SyncTalk/blob/cd85adb1a30da60105984019c1f0c4221f4709bf/nerf_triplane/utils.py#L1077)

**Comment by zckcola** [comment]
> --portrait 是该模块的调用方式，具体实现可以参考[utils.py](https://github.com/ZiqiaoPeng/SyncTalk/blob/cd85adb1a30da60105984019c1f0c4221f4709bf/nerf_triplane/utils.py#L1077)

谢谢，请问这个大概作用是什么呢

**Comment by G-force78** [comment]
> --portrait 是该模块的调用方式，具体实现可以参考[utils.py](https://github.com/ZiqiaoPeng/SyncTalk/blob/cd85adb1a30da60105984019c1f0c4221f4709bf/nerf_triplane/utils.py#L1077)

Thats not the same as the half body example though is it
