### ISSUE TITLE
preprocessing mask face

### ISSUE THREAD

**Issue by primepake** [ZiqiaoPeng/SyncTalk#38]
Thanks for your amazing work!

![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/38185159/9ae81992-196f-4ecf-ad2d-48f54ce7135b)

what is the filter you applied to get the left image after parsing?

**Comment by hitlecapital** [comment]
also how can you extend a bit on the bottom mask?

**Comment by jinqiupeter** [comment]
This worked for me (except the extra bit of neck on the bottom): 
```
    # ------------start to handle face -----------
    # 创建蓝色区域的掩码
    lower_blue = np.array([250, 0, 0])  # 更高的蓝色分量，较低的绿色和红色分量
    upper_blue = np.array([255, 10, 10])  # 上限值也设置成低的绿色和红色分量
    mask = cv2.inRange(face_parsing_color, lower_blue, upper_blue)

    # 使用掩码获取蓝色区域
    blue_face_area = cv2.bitwise_and(face_parsing_color, face_parsing_color, mask=mask)

    # 去除人脸周围的毛刺和凸起，并添加高斯模糊
    # 定义一个核，用于形态学操作
    kernel = np.ones((10,10),np.uint8)
    # 先腐蚀，后膨胀，再高斯模糊
    face_mask_eroded = cv2.erode(blue_face_area, kernel, iterations = 3)
    face_mask_smoothed = cv2.dilate(face_mask_eroded, kernel, iterations = 3)
    mask2 = cv2.inRange(face_mask_smoothed, lower_blue, upper_blue)
    face_mask_smoothed = face_mask_smoothed.astype(np.uint8)

    # 使用掩码将非蓝色区域（背景）设置为白色
    mask_inv = cv2.bitwise_not(mask2)  # 获取掩码的反向掩码
    background = np.full(face_parsing_color.shape, 255, dtype=np.uint8)  # 创建一个全白的背景
    background = cv2.bitwise_and(background, background, mask=mask_inv)  # 将反向掩码应用于全白背景
    final_image = cv2.add(face_mask_smoothed, background)  # 将蓝色区域与背景合并
    final_image = cv2.GaussianBlur(final_image, (11, 11), 0)

    face_vis_im = cv2.resize(final_image, img_size,
                        interpolation=cv2.INTER_NEAREST)
    face_save_path = save_path.replace(".png", "_face.png")
    if save_im:
        cv2.imwrite(face_save_path, face_vis_im)
    
    # ------------ finished handling face 
```

**Comment by jinqiupeter** [comment]
This https://github.com/ZiqiaoPeng/SyncTalk/issues/22 seems to be the neck handling

**Comment by hereTac** [comment]
> This worked for me with help from ChatGPT (except the extra bit of neck on the bottom):
> 
> ```
>     # ------------start to handle face -----------
>     # 创建蓝色区域的掩码
>     lower_blue = np.array([250, 0, 0])  # 更高的蓝色分量，较低的绿色和红色分量
>     upper_blue = np.array([255, 10, 10])  # 上限值也设置成低的绿色和红色分量
>     mask = cv2.inRange(face_parsing_color, lower_blue, upper_blue)
> 
>     # 使用掩码获取蓝色区域
>     blue_face_area = cv2.bitwise_and(face_parsing_color, face_parsing_color, mask=mask)
> 
>     # 去除人脸周围的毛刺和凸起，并添加高斯模糊
>     # 定义一个核，用于形态学操作
>     kernel = np.ones((10,10),np.uint8)
>     # 先腐蚀，后膨胀，再高斯模糊
>     face_mask_eroded = cv2.erode(blue_face_area, kernel, iterations = 3)
>     face_mask_smoothed = cv2.dilate(face_mask_eroded, kernel, iterations = 3)
>     mask2 = cv2.inRange(face_mask_smoothed, lower_blue, upper_blue)
>     face_mask_smoothed = face_mask_smoothed.astype(np.uint8)
> 
>     # 使用掩码将非蓝色区域（背景）设置为白色
>     mask_inv = cv2.bitwise_not(mask2)  # 获取掩码的反向掩码
>     background = np.full(face_parsing_color.shape, 255, dtype=np.uint8)  # 创建一个全白的背景
>     background = cv2.bitwise_and(background, background, mask=mask_inv)  # 将反向掩码应用于全白背景
>     final_image = cv2.add(face_mask_smoothed, background)  # 将蓝色区域与背景合并
>     final_image = cv2.GaussianBlur(final_image, (11, 11), 0)
> 
>     face_vis_im = cv2.resize(final_image, img_size,
>                         interpolation=cv2.INTER_NEAREST)
>     face_save_path = save_path.replace(".png", "_face.png")
>     if save_im:
>         cv2.imwrite(face_save_path, face_vis_im)
>     
>     # ------------ finished handling face 
> ```

@jinqiupeter  Hi. Do u use some face shape modles to detect the face ? shape_predictor_68_face_landmarks  or shape_predictor_81_face_landmarks ? I tried the shape_predictor_81_face_landmarks, it is not good as May's ../data/May/parsing/0_face.png.

**Comment by xcq2000** [comment]
> > This worked for me with help from ChatGPT (except the extra bit of neck on the bottom):
> > ```
> >     # ------------start to handle face -----------
> >     # 创建蓝色区域的掩码
> >     lower_blue = np.array([250, 0, 0])  # 更高的蓝色分量，较低的绿色和红色分量
> >     upper_blue = np.array([255, 10, 10])  # 上限值也设置成低的绿色和红色分量
> >     mask = cv2.inRange(face_parsing_color, lower_blue, upper_blue)
> > 
> >     # 使用掩码获取蓝色区域
> >     blue_face_area = cv2.bitwise_and(face_parsing_color, face_parsing_color, mask=mask)
> > 
> >     # 去除人脸周围的毛刺和凸起，并添加高斯模糊
> >     # 定义一个核，用于形态学操作
> >     kernel = np.ones((10,10),np.uint8)
> >     # 先腐蚀，后膨胀，再高斯模糊
> >     face_mask_eroded = cv2.erode(blue_face_area, kernel, iterations = 3)
> >     face_mask_smoothed = cv2.dilate(face_mask_eroded, kernel, iterations = 3)
> >     mask2 = cv2.inRange(face_mask_smoothed, lower_blue, upper_blue)
> >     face_mask_smoothed = face_mask_smoothed.astype(np.uint8)
> > 
> >     # 使用掩码将非蓝色区域（背景）设置为白色
> >     mask_inv = cv2.bitwise_not(mask2)  # 获取掩码的反向掩码
> >     background = np.full(face_parsing_color.shape, 255, dtype=np.uint8)  # 创建一个全白的背景
> >     background = cv2.bitwise_and(background, background, mask=mask_inv)  # 将反向掩码应用于全白背景
> >     final_image = cv2.add(face_mask_smoothed, background)  # 将蓝色区域与背景合并
> >     final_image = cv2.GaussianBlur(final_image, (11, 11), 0)
> > 
> >     face_vis_im = cv2.resize(final_image, img_size,
> >                         interpolation=cv2.INTER_NEAREST)
> >     face_save_path = save_path.replace(".png", "_face.png")
> >     if save_im:
> >         cv2.imwrite(face_save_path, face_vis_im)
> >     
> >     # ------------ finished handling face 
> > ```
> 
> @jinqiupeter Hi. Do u use some face shape modles to detect the face ? shape_predictor_68_face_landmarks or shape_predictor_81_face_landmarks ? I tried the shape_predictor_81_face_landmarks, it is not good as May's ../data/May/parsing/0_face.png.

use face-parsing:  https://github.com/zllrunning/face-parsing.PyTorch

**Comment by ZiqiaoPeng** [comment]
The face mask code has been released. Thanks for your patience.
