### ISSUE TITLE
Can't install  ./freqencoder ./shencoder  ./gridencoder ./raymarching on Colab

### ISSUE THREAD

**Issue by kieojk** [ZiqiaoPeng/SyncTalk#46]
Can't install  ./freqencoder ./shencoder  ./gridencoder ./raymarching on Colab
![360截图20240321154247012](https://github.com/ZiqiaoPeng/SyncTalk/assets/41268759/0b159580-511e-43a9-9f37-cf2f7dc896aa)

**Comment by ZiqiaoPeng** [comment]
I uploaded Colab notebook, you can try it.
