### ISSUE TITLE
The expressions and head poses for different driving audio clips are the same

### ISSUE THREAD

**Issue by rongliang30** [ZiqiaoPeng/SyncTalk#47]
Hi, thanks for sharing the great work.

I managed to test the model using customized audio clips. However, I noticed that the expressions and head poses for the generated videos follow the same motion pattern (even provided with different audio clips).

Could you please help advise how to generate diverse motions? And is it possible to explicitly control the generated expressions & head poses by user inputs? 

Looking forward to the responses. Thanks!

**Comment by HenryKang1** [comment]
This is Lipsync model. The main purpose of Lipsync is lipmovement in the video and audio sync without artifact. I believe your purpose is different research topic.

**Comment by johndpope** [comment]
related https://yudeng.github.io/Portrait4D-v2/

**Comment by G-force78** [comment]
> This is Lipsync model. The main purpose of Lipsync is lipmovement in the video and audio sync without artifact. I believe your purpose is different research topic.

It is supposed to generate expressions too..
