### ISSUE TITLE
请问face_rect保存着什么特征信息

### ISSUE THREAD

**Issue by zckcola** [ZiqiaoPeng/SyncTalk#48]
rect': raw_sample['face_rect'],
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/145427194/253803ef-d606-4553-8ae4-d77f8e396afd)

**Comment by zckcola** [comment]
以及这里保存的是什么信息
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/145427194/5f92afba-fc74-4cf1-8a2d-6150ce112899)
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/145427194/e517b31d-a061-4d5e-9a5b-e870cf19132a)

**Comment by ThetaRgo** [comment]
> rect': raw_sample['face_rect'], ![image](https://private-user-images.githubusercontent.com/145427194/316792236-253803ef-d606-4553-8ae4-d77f8e396afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjU1MzMsIm5iZiI6MTcxMzI2NTIzMywicGF0aCI6Ii8xNDU0MjcxOTQvMzE2NzkyMjM2LTI1MzgwM2VmLWQ2MDYtNDU1My04YWU0LWQ3N2Y4ZTM5NmFmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMTAwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTI4NjQ0Mjk1NmI2OTQxMjJmYzU0MDQ1Mjg0M2E5Y2UyNTQ2YjQxNjY2ZTBmYWFlNzYxOGZiZmQ3OWRlMWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6K0Ygho1eJqCDBruUSsoLZgV66hKBpCKyaoITbJNDxc)

这段代码在哪个文件，没看到有这行代码。

**Comment by ThetaRgo** [comment]
> 以及这里保存的是什么信息 ![image](https://private-user-images.githubusercontent.com/145427194/316793613-5f92afba-fc74-4cf1-8a2d-6150ce112899.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjU1MzMsIm5iZiI6MTcxMzI2NTIzMywicGF0aCI6Ii8xNDU0MjcxOTQvMzE2NzkzNjEzLTVmOTJhZmJhLWZjNzQtNGNmMS04YTJkLTYxNTBjZTExMjg5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMTAwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Zjk2MzFhYWZiZWY5ZDAwN2U4YWY3YjU4ZTIzMTgzZmNiYTcyM2MyOWZjZGM3NDRlNzZiYzQwNTI5NzM0ODIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CJHIxvvpDFZjLaPOIEQCmJbqogU-86gF8wa_D2d5pQA) ![image](https://private-user-images.githubusercontent.com/145427194/316793757-e517b31d-a061-4d5e-9a5b-e870cf19132a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjU1MzMsIm5iZiI6MTcxMzI2NTIzMywicGF0aCI6Ii8xNDU0MjcxOTQvMzE2NzkzNzU3LWU1MTdiMzFkLWEwNjEtNGQ1ZS05YTViLWU4NzBjZjE5MTMyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMTAwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWQ0MjRiYWRmMDM3YTJhYTMyNGE3OGEzYzQ1NDFmNWJlZjU4YmJhNDQwNGI5Njc2MjNjYmJhOGY3MzBhNmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IDaQP2kI4Z6QYfZeRC7cV01OzuFRkEKuvwQ0qHAvkpg)

脸部坐标信息
