### ISSUE TITLE
请问使用了什么方法将生成的视频头部拼回半身视频呢？

### ISSUE THREAD

**Issue by Chichibabin** [ZiqiaoPeng/SyncTalk#49]
您好！想咨询一下在项目主页展示的视频中有May的半身视频中，是如何将生成的头部贴合原视频的身体的？

**Comment by jinqinn** [comment]
同问

**Comment by yangzhidao** [comment]
> 您好！想咨询一下在项目主页展示的视频中有May的半身视频中，是如何将生成的头部贴合原视频的身体的？

请问你如何处理得到的ave.npy文件？

**Comment by jeromecn** [comment]
看代码应该是生成了一组原始视频分辨率大小的头部遮罩，生成的过程中进行蒙版处理

**Comment by jinqinn** [comment]
@jeromecn 是哪段代码呢？学习下，谢谢

**Comment by jinqinn** [comment]
@Chichibabin 你实现了吗

**Comment by Chichibabin** [comment]
> 看代码应该是生成了一组原始视频分辨率大小的头部遮罩，生成的过程中进行蒙版处理

原来如此，感谢回答！

**Comment by Chichibabin** [comment]
> @Chichibabin 你实现了吗

我还没有实现，但感觉原理上与这个issues分享的方法类似：https://github.com/yerfor/GeneFacePlusPlus/issues/138

**Comment by jinqinn** [comment]
@Chichibabin 这个方法不能解决原视频中身体部位的抖动问题

**Comment by Chichibabin** [comment]
> @Chichibabin 这个方法不能解决原视频中身体部位的抖动问题

确实，我现在也在尝试解决这个问题。

**Comment by jinqinn** [comment]
@Chichibabin  方便加个wx吗？ 一起探讨下

**Comment by Chichibabin** [comment]
方便的，我的微信号：wxid_05netnv1ccs122
________________________________
发件人: jinqinn ***@***.***>
发送时间: 2024年3月28日 13:28
收件人: ZiqiaoPeng/SyncTalk ***@***.***>
抄送: Chio ***@***.***>; Mention ***@***.***>
主题: Re: [ZiqiaoPeng/SyncTalk] 请问使用了什么方法将生成的视频头部拼回半身视频呢？ (Issue #49)


@Chichibabin<https://github.com/Chichibabin> 方便加个wx吗？ 一起探讨下

―

**Comment by Chichibabin** [comment]
> @Chichibabin 方便加个wx吗？ 一起探讨下

方便的，我的微信号：wxid_05netnv1ccs122

**Comment by jinqinn** [comment]
@Chichibabin  微信号是不是打错了，怎么搜索不到

**Comment by Chichibabin** [comment]
> @Chichibabin 微信号是不是打错了，怎么搜索不到

抱歉，好像微信不能通过wxid开头的微信号搜索用户。麻烦您再搜一下：github_chichibabin

**Comment by HonestQiao** [comment]
> > @Chichibabin 微信号是不是打错了，怎么搜索不到
> 
> 抱歉，好像微信不能通过wxid开头的微信号搜索用户。麻烦您再搜一下：github_chichibabin
已加！

**Comment by rongliang30** [comment]
Hi, 请问下你有原版May的半身视频吗？我想也尝试一下把生成的图片拼接回去。希望可以分享一下， 谢谢！

**Comment by HonestQiao** [comment]
> Hi, 请问下你有原版May的半身视频吗？我想也尝试一下把生成的图片拼接回去。希望可以分享一下， 谢谢！

我有其他的，你这边已经有合成的方法和脚本了吗？
我的微信：HonestQiao
