### ISSUE TITLE
The issue with self.auds during data loading

### ISSUE THREAD

**Issue by xiaoniuchushi** [ZiqiaoPeng/SyncTalk#54]
Should aud_features also distinguish between train and test data when loading them, rather than loading them all.
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/10252589/6d1f715f-9af7-4d84-a078-96aba0158303)

https://github.com/ZiqiaoPeng/SyncTalk/blob/9ca6a0dd4bdf5c3cd4b571af31265a11e8e9e0d5/nerf_triplane/provider.py#L412

**Comment by ZiqiaoPeng** [comment]
This does not affect training and testing.
