### ISSUE TITLE
issue of installing on whindows 10? 

### ISSUE THREAD

**Issue by xunnew** [ZiqiaoPeng/SyncTalk#56]
pytorch3d issue

  self.initialize_options()
running bdist_egg
running egg_info
writing pytorch3d.egg-info\PKG-INFO
writing dependency_links to pytorch3d.egg-info\dependency_links.txt
writing entry points to pytorch3d.egg-info\entry_points.txt
writing requirements to pytorch3d.egg-info\requires.txt
writing top-level names to pytorch3d.egg-info\top_level.txt
reading manifest file 'pytorch3d.egg-info\SOURCES.txt'
adding license file 'LICENSE'
adding license file 'LICENSE-3RD-PARTY'
writing manifest file 'pytorch3d.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
error: [WinError 2] 系统找不到指定的文件。

**Comment by ZiqiaoPeng** [comment]
You can try the Windows integration package now.
