### ISSUE TITLE
--portrait  推理结果仍然是大头贴，没有带下半身。

### ISSUE THREAD

**Issue by CatherineZhou** [ZiqiaoPeng/SyncTalk#58]
我也遇到同样问题，readme中提到““portrait” signifies pasting the generated face back onto the original image”， 但是，用“python main.py data/May --workspace model/trial_may -O --test --test_train --asr_model ave --portrait --aud ./demo/test.wav ”生成result文件没有带下半身，只有大头贴。谁能帮忙解答下。

**Comment by jinqiupeter** [comment]
这里说的 back onto the original image指的是back into 训练用的512x512视频。要贴回原来带下半身的视频的话要用代码来识别人脸，然后基于人脸位置剪辑出512x512的视频，记住人脸位置，然后把生成出来的视频再根据保存的位置贴回原来的全身视频

**Comment by a3131919** [comment]
可以更詳細說一下嗎? 目前的理解是頭部一定要512x512　然後通過某些方法調整下半身?

**Comment by Skye2099** [comment]
> > 这里说的 back onto the original image指的是back into 训练用的512x512视频。要贴回原来带下半身的视频的话要用代码来识别人脸，然后基于人脸位置剪辑出512x512的视频，记住人脸位置，然后把生成出来的视频再根据保存的位置贴回原来的全身视频
> 
> 正解，下半身的视频可以用ffmpeg按照裁剪的像素贴回去，或者使用adobe pr/final cut pro等剪辑软件贴回。

贴回去后有个矩形的阴影应该咋解决？
