### ISSUE TITLE
Character not blinking when testing on my custom trained model

### ISSUE THREAD

**Issue by yc4ny** [ZiqiaoPeng/SyncTalk#62]
Hi, thanks for the great work and opensourcing it. 
I've written the preprocess code and verified that it works good on the demo May .mp4 file. 
However, when I use my custom data and train, it doesn't seem to blink. 
BTW I've extracted the blendshape (bs.npy) file from EmoTalk. 

Thanks

**Comment by jinqiupeter** [comment]
What I did is to only use the lower part of the face when generating the face mask (used in blend_with_mask_cuda) so the generated video will have the same eye blink, eyebrow movements, etc.

**Comment by yc4ny** [comment]
> What I did is to only use the lower part of the face when generating the face mask (used in blend_with_mask_cuda) so the generated video will have the same eye blink, eyebrow movements, etc.

@jinqiupeter Thanks for the reply. Do you mean by the lower part of the face the part of face without the hair? Just like the part where we obtain the face(diluted blue) in parsing?

**Comment by jinqiupeter** [comment]
Yes, without hair, otherwise hair will be blurry. blend_with_mask_cuda uses the *_face.jpg|png in the parsing folder

**Comment by kike-0304** [comment]
> Yes, without hair, otherwise hair will be blurry. blend_with_mask_cuda uses the *_face.jpg|png in the parsing folder

May I ask how you resolved the issue of inconsistent facial skin tone between the original and generated videos？

**Comment by ZiqiaoPeng** [comment]
You can try the latest code.
