### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by balogistvan** [ZiqiaoPeng/SyncTalk#65]
First of all, thank you for your work.
My problem is that when I try to train the model, I get an error.
The error i get when I use own data or May.
![Untitled](https://github.com/ZiqiaoPeng/SyncTalk/assets/112938298/1da0b4f8-dd4f-4e80-ba07-e8751123c05e)

**Comment by ZiqiaoPeng** [comment]
I fixed this bug. Thanks.
