### ISSUE TITLE
执行python main.py data/m2fp --workspace model/trial_m2fp -O --iters 60000 --asr_model ave 报错。

### ISSUE THREAD

**Issue by wanghx1121** [ZiqiaoPeng/SyncTalk#68]
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/159092899/348052fa-ac77-405d-95f5-3ee8152ace39)
请帮忙看一下，谢谢！@ZiqiaoPeng

**Comment by ZiqiaoPeng** [comment]
这个bug已经被修复了，请重新pull仓库。

**Comment by wanghx1121** [comment]
> 这个bug已经被修复了，请重新pull仓库。

谢谢，我试一下
