### ISSUE TITLE
FakeOpen?

### ISSUE THREAD

**Issue by piwawa** [ZiqiaoPeng/SyncTalk#7]
right?

**Comment by tianlinzx** [comment]
Wrong.

**Comment by tianlinzx** [comment]
Yes.

**Comment by marcelgoya** [comment]
Any update on the release of the code?

**Comment by Inferencer** [comment]
> right?

What it is.. is they submit their paper to CVPR (Computer Vision and Pattern Recognition Conference) when it gets accepted they release the code, the dates on which this could get accepted vary so could be within a couple more months. they need repos so people can watch and wait for code release & ask questions about paper and have links to project pages for more results etc

**Comment by marcelgoya** [comment]
@Inferencer Thanks for the heads up, guess we'll have to wait until the end of February then ...

**Comment by xiaozhi2015** [comment]
> @Inferencer Thanks for the heads up, guess we'll have to wait until the end of February then ...

@marcelgoya How time flies. It's already the end of February.

**Comment by ZiqiaoPeng** [comment]
The code has been released. Thank you for your patience.

**Comment by marcelgoya** [comment]
@ZiqiaoPeng Thank you very much!

**Comment by piwawa** [comment]
> The code has been released. Thank you for your patience.

I take back what I said, salute you!
