### ISSUE TITLE
请问训练的时候是否碰到过这个

### ISSUE THREAD

**Issue by BarryZM** [ZiqiaoPeng/SyncTalk#71]
<img width="781" alt="image" src="https://github.com/ZiqiaoPeng/SyncTalk/assets/26347137/c73029f0-08c4-4963-8c5c-b8d41f927d35">

**Comment by BarryZM** [comment]
是不是我数据有问题，梯度爆炸了啊

**Comment by wuzhongdehua** [comment]
+1

**Comment by ZiqiaoPeng** [comment]
重新pull一下代码，再运行一次数据预处理的过程，刚修复了一个tracker代码的bug。

**Comment by jinqiupeter** [comment]
也可能学习率太大了，main.py里面可以通过参数调整

**Comment by BarryZM** [comment]
好的，我试一下，感谢

**Comment by wning13** [comment]
> 重新pull一下代码，再运行一次数据预处理的过程，刚修复了一个tracker代码的bug。

请问，您能告诉我这个问题发生的原因以及需要做出修改的原因吗？

**Comment by wennjiee** [comment]
我也遇到了这个问题，我通过debug发现是在以下出现了bug，输出的feat_xy是nan
`       feat_xy = self.encoder_xy(xy, bound=bound)
        feat_yz = self.encoder_yz(yz, bound=bound)
        feat_xz = self.encoder_xz(xz, bound=bound)
`
此外我在此处除法分母增加了小数，防止nan
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/68308198/dca38249-1408-48ee-b7ac-40c01ea494af)
但是，我的loss收敛情况不太良好，在0.008左右徘徊，不太清楚具体原因

**Comment by ZiqiaoPeng** [comment]
修复了一些bug，请重新pull代码，并从头开始运行数据预处理，再进行训练。

**Comment by StephanPan** [comment]
用其他视频数据还是有这个问题

**Comment by lipsynthesis** [comment]
> I still have this problem when using other video data

Reinstalling full environment with most recent commit helped me.
