### ISSUE TITLE
生成视频头部相对稳定，但是嘴唇抖动比较严重，又遇到相同问题的伙伴吗

### ISSUE THREAD

**Issue by yulj21** [ZiqiaoPeng/SyncTalk#74]

**Comment by WoJiaoFuXiaoYun** [comment]
是的没错，最新代码嘴唇确实不自然

**Comment by yulj21** [comment]
@ZiqiaoPeng  作者您好，请问输入视频的人像大小有要求吗，这个是否会影响嘴唇生成效果

**Comment by kike-0304** [comment]
嘴唇抖动很大，眼睛不眨

**Comment by ZiqiaoPeng** [comment]
AVE适合嘴唇同步准确且嘴唇运动大的角色，例如May和Shaheen。嘴唇闪动的问题可以考虑使用deepspeech的特征，在最新代码已经支持调用。

**Comment by schxnhxlz** [comment]
does anyone solved the lip jittering?
