### ISSUE TITLE
用May复现结果，发现还是嘴部生成不对

### ISSUE THREAD

**Issue by yulj21** [ZiqiaoPeng/SyncTalk#77]
https://github.com/ZiqiaoPeng/SyncTalk/assets/92900714/3618a4ae-6e47-4ee7-9432-d901472f31f9

**Comment by yulj21** [comment]
https://github.com/ZiqiaoPeng/SyncTalk/assets/92900714/f81c1e33-79d9-4d34-8e1b-6360abb0a301

**Comment by yulj21** [comment]
https://github.com/ZiqiaoPeng/SyncTalk/assets/92900714/9ace6a3a-1e67-41c8-929c-24198654a654

**Comment by ZiqiaoPeng** [comment]
我这边用May的视频反复测试了多次，都是没有问题的
<img width="509" alt="iShot_2024-04-30_22 47 18" src="https://github.com/ZiqiaoPeng/SyncTalk/assets/93774583/20b32375-7773-4529-982b-425b26990f4a">

**Comment by yulj21** [comment]
我用的是我自己训练的模型，结果如上图 感觉哪里不对 明天我把我的tensorboard截图发下吧

**Comment by yulj21** [comment]
![30d973a18e0446fdd75a2dc2813065eb](https://github.com/ZiqiaoPeng/SyncTalk/assets/92900714/18c6ab1c-9e3e-4e27-8120-45996a9e13a8)
![14c18cf7fa5141306ed466f3459ae5ac](https://github.com/ZiqiaoPeng/SyncTalk/assets/92900714/a3a2b9eb-2066-44af-86dc-4e7059b14615)

这是自己训练may视频的tensorboard

**Comment by Tiandishihua** [comment]
> 我这边用May的视频反复测试了多次，都是没有问题的 <img alt="iShot_2024-04-30_22 47 18" width="509" src="https://private-user-images.githubusercontent.com/93774583/326854994-20b32375-7773-4529-982b-425b26990f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MTIxNzcsIm5iZiI6MTcxNDgxMTg3NywicGF0aCI6Ii85Mzc3NDU4My8zMjY4NTQ5OTQtMjBiMzIzNzUtNzc3My00NTI5LTk4MmItNDI1YjI2OTkwZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDA4Mzc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NzA2OTYwN2NkNGFiMjIyOTljNjIxMjUxMjkwYzIwODI2NjBjODljNWI1NTMxYTE1MGRmNDZkOGQwYzgzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S9IEWqBGVr80s8CGnipwwcwWKHwvNS35TEppBFMOj1o">

我也是自己制作数据集，结果训练得到的嘴部动作不对

**Comment by Tiandishihua** [comment]
> 我这边用May的视频反复测试了多次，都是没有问题的 <img alt="iShot_2024-04-30_22 47 18" width="509" src="https://private-user-images.githubusercontent.com/93774583/326854994-20b32375-7773-4529-982b-425b26990f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODkwNzEsIm5iZiI6MTcxNDk4ODc3MSwicGF0aCI6Ii85Mzc3NDU4My8zMjY4NTQ5OTQtMjBiMzIzNzUtNzc3My00NTI5LTk4MmItNDI1YjI2OTkwZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA5NDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YTAzODA3NmQ3MzA2MDVlMTIyNTg5ODBhZGM1MTJhZjZlMjMxMDBjZGUxYzM1OGUzMDk1ZDJkNjNlYjRkYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GkBT514V0W2wglWYLl0rMCxYwzMChdSfGQr869ieDHw">

作者，您好！我已经使用你最新的代码，结果还是训练不成功，出现loss nan现象，我按照你的建议torch.exp(torch.clamp(h[..., 0], -9.0, 9.0))结果训练出的嘴部动作很糟糕，我问过几个人，都没有训练成功过，请问可能什么原因造成的。

**Comment by yulj21** [comment]
> > 我这边用May的视频反复测试了多次，都是没有问题的 <img alt="iShot_2024-04-30_22 47 18" width="509" src="https://private-user-images.githubusercontent.com/93774583/326854994-20b32375-7773-4529-982b-425b26990f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODkwNzEsIm5iZiI6MTcxNDk4ODc3MSwicGF0aCI6Ii85Mzc3NDU4My8zMjY4NTQ5OTQtMjBiMzIzNzUtNzc3My00NTI5LTk4MmItNDI1YjI2OTkwZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA5NDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YTAzODA3NmQ3MzA2MDVlMTIyNTg5ODBhZGM1MTJhZjZlMjMxMDBjZGUxYzM1OGUzMDk1ZDJkNjNlYjRkYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GkBT514V0W2wglWYLl0rMCxYwzMChdSfGQr869ieDHw">
> 
> 作者，您好！我已经使用你最新的代码，结果还是训练不成功，出现loss nan现象，我按照你的建议torch.exp(torch.clamp(h[..., 0], -9.0, 9.0))结果训练出的嘴部动作很糟糕，我问过几个人，都没有训练成功过，请问可能什么原因造成的。

你也是用May的视频训练的吗，我感觉是哪个参数设置有问题，但是就是一直找不到原因

**Comment by Tiandishihua** [comment]
> > > 我这边用May的视频反复测试了多次，都是没有问题的 <img alt="iShot_2024-04-30_22 47 18" width="509" src="https://private-user-images.githubusercontent.com/93774583/326854994-20b32375-7773-4529-982b-425b26990f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODkwNzEsIm5iZiI6MTcxNDk4ODc3MSwicGF0aCI6Ii85Mzc3NDU4My8zMjY4NTQ5OTQtMjBiMzIzNzUtNzc3My00NTI5LTk4MmItNDI1YjI2OTkwZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA5NDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YTAzODA3NmQ3MzA2MDVlMTIyNTg5ODBhZGM1MTJhZjZlMjMxMDBjZGUxYzM1OGUzMDk1ZDJkNjNlYjRkYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GkBT514V0W2wglWYLl0rMCxYwzMChdSfGQr869ieDHw">
> > 
> > 
> > 作者，您好！我已经使用你最新的代码，结果还是训练不成功，出现loss nan现象，我按照你的建议torch.exp(torch.clamp(h[..., 0], -9.0, 9.0))结果训练出的嘴部动作很糟糕，我问过几个人，都没有训练成功过，请问可能什么原因造成的。
> 
> 你也是用May的视频训练的吗，我感觉是哪个参数设置有问题，但是就是一直找不到原因

我用的马克龙视频，不过其他人用自己的视频也是loss nan等各种问题

**Comment by ZiqiaoPeng** [comment]
目前定位到是mediapipe面捕的blendshape不准导致的，现在正在寻找替代品。

**Comment by yulj21** [comment]
> 目前定位到是mediapipe面捕的blendshape不准导致的，现在正在寻找替代品。

期待你的解决

**Comment by ZiqiaoPeng** [comment]
可以把训练loss为nan的视频发送到pengziqiao@ruc.edu.cn
我会尝试训练之后给大家反馈

**Comment by piwawa** [comment]
> 目前定位到是mediapipe面捕的blendshape不准导致的，现在正在寻找替代品。

[EmoTalk](https://github.com/psyai-net/EmoTalk_release) 不是开源了吗？为啥不直接用他的面捕模块？

**Comment by Tiandishihua** [comment]
> > 目前定位到是mediapipe面捕的blendshape不准导致的，现在正在寻找替代品。
> 
> [EmoTalk](https://github.com/psyai-net/EmoTalk_release) 不是开源了吗？为啥不直接用他的面捕模块？
那个适配的权重没有开源

**Comment by ZiqiaoPeng** [comment]
loss为nan的问题已经修复，请pull最新代码。
