### ISSUE TITLE
keypoints.txt input contained no data

### ISSUE THREAD

**Issue by einsqing** [ZiqiaoPeng/SyncTalk#82]
UserWarning: loadtxt: input contained no data: "data/0228/keypoints.txt"
  key_xys = np.loadtxt(os.path.join(base_dir, 'keypoints.txt'), np.int32)

**Comment by hasanshahid5678** [comment]
Yeah same issue, no keypoints were found in the txt file unlike for some other videos I preprocessed.

**Comment by G-force78** [comment]
Same here, first time had this error

**Comment by G-force78** [comment]
Ive trained again and now have them but they are way off, for some strange reason they are located on the side of the  head solution? 
![keypts](https://github.com/ZiqiaoPeng/SyncTalk/assets/114336644/7b89c10b-ed93-42fc-95a0-5c1a02c112ec)

**Comment by hasanshahid5678** [comment]
Don't know if the keypoints are okay in each of them. And the keypoints are generated in some cases and in some cases do not.

**Comment by ZiqiaoPeng** [comment]
It is only suitable for 512*512 resolution and the face is real and clear.

**Comment by NithinJangid** [comment]
my video is of resolution (512, 512) and but still the key points file is empty. How did you solve?
