### ISSUE TITLE
使用deepspeech模式训练，没有aud_ds.npy

### ISSUE THREAD

**Issue by JYC1012** [ZiqiaoPeng/SyncTalk#86]
`(synctalk) jingyc@sugon-X640-G40:/data2/jingyc/SyncTalk$ CUDA_VISIBLE_DEVICES=7 python main.py data/chenguang --workspace model/trial_chenguang -O --iters 60000 --asr_model deepspeech
Namespace(H=450, O=True, W=450, amb_aud_loss=1, amb_dim=2, amb_eye_loss=1, asr=False, asr_model='deepspeech', asr_play=False, asr_save_feats=False, asr_wav='', att=2, aud='', bg_img='', bound=1, bs_area='upper', ckpt='latest', color_space='srgb', cuda_ray=True, data_range=[0, -1], density_thresh=10, density_thresh_torso=0.01, dt_gamma=0.00390625, emb=False, exp_eye=True, fbg=False, finetune_lips=False, fix_eye=-1, fovy=21.24, fp16=True, fps=50, gui=False, head_ckpt='', ind_dim=4, ind_dim_torso=8, ind_num=20000, init_lips=False, iters=60000, l=10, lambda_amb=0.1, lr=0.01, lr_net=0.001, m=50, max_ray_batch=4096, max_spp=1, max_steps=16, min_near=0.05, num_rays=65536, num_steps=16, offset=[0, 0, 0], part=False, part2=False, patch_size=1, path='data/chenguang', portrait=False, preload=0, pyramid_loss=0, r=10, radius=3.35, scale=4, seed=0, smooth_eye=False, smooth_lips=False, smooth_path=False, smooth_path_window=7, test=False, test_train=False, torso=False, torso_shrink=0.8, train_camera=False, unc_loss=1, update_extra_interval=16, upsample_steps=0, warmup_step=10000, workspace='model/trial_chenguang')
[INFO] load 1400 train frames.
Traceback (most recent call last):
  File "main.py", line 219, in <module>
    train_loader = NeRFDataset(opt, device=device, type='train').dataloader()
  File "/data2/jingyc/SyncTalk/nerf_triplane/provider.py", line 166, in __init__
    aud_features = np.load(os.path.join(self.root_path, 'aud_ds.npy'))
  File "/home/jingyc/.conda/envs/synctalk/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/chenguang/aud_ds.npy'
`

**Comment by wyrcode** [comment]
怎么解决的呢？我这边也遇到了这个问题

**Comment by 11898d** [comment]
python data_utils/deepspeech_features/extract_ds_features.py --input data/<name>.wav # save to data/<name>.npy
使用这个命令可以转换成npy格式的
