### ISSUE TITLE
代码在上传吗？它训练快速吗

### ISSUE THREAD

**Issue by juntaosun** [ZiqiaoPeng/SyncTalk#9]
感谢你们杰出的工作。
代码在上传吗？它训练快速吗。

---

Thank you for your outstanding work.
Is the code being uploaded? Does it train quickly?

---

**Comment by ZiqiaoPeng** [comment]
代码已发布，感谢耐心等待。训练使用Nvidia RTX 3090大约需要2个小时。

The code has been released, thank you for your patience. It takes about 2 hours to train to use Nvidia RTX 3090 GPU.
