### ISSUE TITLE
invalid value encountered in cast

### ISSUE THREAD

**Issue by einsqing** [ZiqiaoPeng/SyncTalk#91]
SyncTalk/nerf_triplane/utils.py:1409: RuntimeWarning: invalid value encountered in divide
  pred_ambient_eye /= np.max(pred_ambient_eye)
SyncTalk/nerf_triplane/utils.py:1422: RuntimeWarning: invalid value encountered in cast
  cv2.imwrite(save_path_ambient_eye, (pred_ambient_eye * 255).astype(np.uint8))
loss=0.0275 (0.0184): : 100% 100/100 [00:18<00:00,  5.40it/s]

**Comment by ZiqiaoPeng** [comment]
It has been fixed.

**Comment by qwert1887** [comment]
SyncTalk/nerf_triplane/utils.py:1084: RuntimeWarning: invalid value encountered in cast
  pred_depth = (pred_depth * 255).astype(np.uint8)
  
I encountered the same bug.Can you share how to fixed,Thanks. @ZiqiaoPeng
