### ISSUE TITLE
Unstable training using private data

### ISSUE THREAD

**Issue by UdonDa** [ZiqiaoPeng/SyncTalk#92]
Hi, 

I have a problem with unstable training using my private data. According to a plot of training losses, the training seems wrong. 
I would like to find out what caused that problem.
Does anyone successfully train your private data?

```bash
# Pre-processing for data
python data_utils/process.py "data/tanaka_moe/tanaka_moe"

# Train
export CUDA_VISIBLE_DEVICES=0
dataset="tanaka_moe"
asr_model="ave"
workspace="results/${dataset}_${asr_model}"
python main.py data/$dataset --workspace $workspace -O --iters 60000 --asr_model $asr_model --preload 1
```

## Epoch 4
![ngp_ep0004_0075_rgb](https://github.com/ZiqiaoPeng/SyncTalk/assets/25411643/93fff496-2eb3-4950-a2c6-021a6e05c3a7)

## Epoch 16
![ngp_ep0016_0004_rgb](https://github.com/ZiqiaoPeng/SyncTalk/assets/25411643/da1e65fe-ba0f-404d-a3c7-4407b1fc5609)

<img width="1057" alt="Screenshot 2024-05-06 21 21 23" src="https://github.com/ZiqiaoPeng/SyncTalk/assets/25411643/22eff59e-2ade-4653-9a76-92c9c4241f8e">

The training video is below,
https://github.com/ZiqiaoPeng/SyncTalk/assets/25411643/c2e10fa5-78be-44b0-a42d-bf697829062d

**Comment by Akatukiaoki** [comment]
![tmpBA4](https://github.com/ZiqiaoPeng/SyncTalk/assets/138298339/25490e8f-1f3a-4646-886a-29d960d4411f)
这怎么解决啊.每次一个epoch跑完就报No faces were detected.的错误

**Comment by UdonDa** [comment]
@Akatukiaoki Can you use English? I'm not Chinese. 
Are you repeating the same question over and over in my issue? I think that your error is happening because you failed to generate the correct faces at the evaluation stage, probably because the training has a problem as in my case.

**Comment by Akatukiaoki** [comment]
> 你会说英语吗？我不是中国人。您是否在我的问题中一遍又一遍地重复相同的问题？我认为您的错误之所以发生，是因为您未能在评估阶段生成正确的面孔，可能是因为训练有问题，就像我的情况一样。
This problem seems very common. I found a solution on other forums and it can now run. May I ask what software or code you used during the training? My English is very poor

**Comment by Akatukiaoki** [comment]
@UdonDa This problem seems very common. I found a solution on other forums and it can now run. May I ask what software or code you used during the training?Your chart looks cool. My English is very poor

**Comment by UdonDa** [comment]
@Akatukiaoki 
> I found a solution on other forums and it can now run.

Where? Could you share it with me?

This chart is plotted by Tensorboard. You can see it in `run/ngp/events.out.tfevents....`. To visualize it, you run `tensorboard --logdir .`

**Comment by Akatukiaoki** [comment]
@UdonDa I only discovered the problems I encountered myself, and I cannot understand your problem. I don't know why this situation occurred. I am just a beginner in this field

**Comment by UdonDa** [comment]
@Akatukiaoki 
Can you successfully train a model with your private data?
If you don't mind, could you please share the video file you are using? There might be something wrong with my video.

**Comment by Akatukiaoki** [comment]
@UdonDa You can try using May to retrain and give it a try.I have encountered a problem. There is no ngp.pth file in my folder, and I am wondering how to obtain it

**Comment by UdonDa** [comment]
I re-preprocess `May` and re-train SyncTalk. As in discussed other issues (#77),  the pre-processing using `mediapipe` causes the problem of quality degradation, according to my training log.
PSNR should be over 37, but this log has 32.

Anyways, I cannot understand why the training with `my private video` failed while the training with `May` was successful.

<img width="471" alt="Screenshot 2024-05-07 12 12 18" src="https://github.com/ZiqiaoPeng/SyncTalk/assets/25411643/5910e880-e2dd-4bf9-bdcd-deaa81c9e4d9">


## Tensorboard plot
<img width="948" alt="Screenshot 2024-05-07 12 11 41" src="https://github.com/ZiqiaoPeng/SyncTalk/assets/25411643/5429fdaa-2c58-44c9-afee-d03ce910518c">

**Comment by UdonDa** [comment]
@Akatukiaoki You should see `<result_dir>/checkpoints`. It is just a weight file.

**Comment by Akatukiaoki** [comment]
This is my folder, he doesn't have ngp.pth
![tmp3DB](https://github.com/ZiqiaoPeng/SyncTalk/assets/138298339/d2f061c1-b5af-4a71-b6df-6eb299062cf1)

**Comment by UdonDa** [comment]
Please try to rename

**Comment by G-force78** [comment]
Bad results here too, what is best practice for data prep? 

https://github.com/ZiqiaoPeng/SyncTalk/assets/114336644/bc84ce97-ceac-4e6d-97a6-c9bb793ba02b

**Comment by UdonDa** [comment]
I changed to use `hubert` and `ER-NeRF's pre-processing, i.e. OpenFace`. Training works well, but, lip sync is not enough.

https://github.com/ZiqiaoPeng/SyncTalk/assets/25411643/1eeaf494-caf7-4c8d-8c89-ea83bbe03fd0

**Comment by Akatukiaoki** [comment]
@UdonDa Can increasing the number of training sessions increase the stability of the mouth? Yesterday, I trained on the Obama video, 60000 times for the head and 90000 times for the mouth, but the mouth is still blurry and has a slight flicker

**Comment by HenryKang1** [comment]
For the best practice, good preprocessing.
There can be many failure cases. ( I saw some artifact because video failed to make accurate mask)
Also good syc of video and audio as original.
Fianlly Good blending algorithm 
Those three are key point for good video generation generally.

**Comment by UdonDa** [comment]
@HenryKang1 Thanks advicing! I agree with you, BEST PRE-PROCESSING IS ALL YOU NEED.

> good preprocessing

How do you pre-process your private video to crop facial region? I follow the pre-processing of [CelebV-HQ's one](https://github.com/CelebV-HQ/CelebV-HQ/issues/16), which is as same as [FirstOrderModel's one](https://github.com/AliaksandrSiarohin/first-order-model/blob/master/crop-video.py). I set increase=0.4.

**Comment by ZiqiaoPeng** [comment]
> ![tmpBA4](https://private-user-images.githubusercontent.com/138298339/328354849-25490e8f-1f3a-4646-886a-29d960d4411f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzY0NTgsIm5iZiI6MTcxNTIzNjE1OCwicGF0aCI6Ii8xMzgyOTgzMzkvMzI4MzU0ODQ5LTI1NDkwZThmLTFmM2EtNDY0Ni04ODZhLTI5ZDk2MGQ0NDExZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwNjI5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTFiY2IxYTc3YTA2ZmUwYzNlNmUzZjA1OGE0YTIxNzc2Nzg0MzZjZWVjYzZmMjNlMzkxZjNhMDUyNWJhNWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6QpVItlY1NiKC1mSMJjKcP5Ekm-sjlTAjbIpE75nhrA) 这怎么解决啊.每次一个epoch跑完就报No faces were detected.的错误

It has been fixed.

**Comment by HenryKang1** [comment]
> @HenryKang1 Thanks advicing! I agree with you, BEST PRE-PROCESSING IS ALL YOU NEED.
> 
> > good preprocessing
> 
> How do you pre-process your private video to crop facial region? I follow the pre-processing of [CelebV-HQ's one](https://github.com/CelebV-HQ/CelebV-HQ/issues/16), which is as same as [FirstOrderModel's one](https://github.com/AliaksandrSiarohin/first-order-model/blob/master/crop-video.py). I set increase=0.4.

I do the similar things. I have my own custom module with padding and resizing function. Try to crop the face with entire face, neck and hair or at least include the neck. Also, training short video does not give good result. try to train longer than 1 min video. Finally apply post processing to remove the artifact.

**Comment by ZiqiaoPeng** [comment]
You can try the latest code.

**Comment by reputationMK** [comment]
@Akatukiaoki 您好，我也碰到了No faces were detected.的错误，请问您是如何解决的？十分感谢！

**Comment by shounakthevoicing** [comment]
https://github.com/ZiqiaoPeng/SyncTalk/assets/173535969/1ef93280-8775-4073-894c-eea3a537af20

@UdonDa I am getting bad results after training for 200k steps total, can you give a link or guide me on how you used ER-NeRF's pre-processing, i.e. OpenFace?

**Comment by Deltaidiots** [comment]
@UdonDa if you can share your preprocessing code that would be very helpful thanks
