### ISSUE TITLE
Preprocess my video empty folders

### ISSUE THREAD

**Issue by vikolaz** [ZiqiaoPeng/SyncTalk#93]
when I preprocess my video the folders face_mask parsing etc are empty, why is that?

Thanks!!

**Comment by ZiqiaoPeng** [comment]
Please provide more detailed error information.

**Comment by Jenkit-Lau** [comment]
> Please provide more detailed error information.

I encountered a similar issue, but after running process.py, the 'face_mask' directory wasn't created, and there were no face mask images (*_face.png) in the 'parsing' folder, only upper body mask images. There were no errors reported during the execution of process.py.

[INFO] ===== extracted images =====
[INFO] ===== extract semantics from data/john/ori_imgs to data/john/parsing =====
[INFO] loading model...
100%|███████████████████████████████████████████████████████████████████████████████| 9353/9353 [04:51<00:00, 32.10it/s]
[INFO] ===== extracted semantics =====
[INFO] ===== extract background image from data/john/ori_imgs =====
100%|█████████████████████████████████████████████████████████████████████████████████| 468/468 [01:45<00:00,  4.43it/s]
[INFO] ===== extracted background image =====
[INFO] ===== extract torso and gt images for data/john =====
100%|███████████████████████████████████████████████████████████████████████████████| 9353/9353 [03:14<00:00, 48.16it/s]
[INFO] ===== extracted torso and gt images =====
[INFO] ===== extract face landmarks from data/john/ori_imgs =====
100%|███████████████████████████████████████████████████████████████████████████████| 9353/9353 [05:25<00:00, 28.75it/s]
[INFO] ===== extracted face landmarks =====
[INFO] ===== perform face tracking =====
[INFO] fitting focal length...
600 2.741929769515991 -3.146671772003174
700 2.7105560302734375 -3.6651816368103027
800 2.6994707584381104 -4.224196434020996
900 2.6857540607452393 -4.75376558303833
1000 2.6793482303619385 -5.298780918121338
1100 2.669788360595703 -5.830570697784424
1200 2.660076379776001 -6.354681968688965
1300 2.6623737812042236 -6.9503374099731445
1400 2.652514934539795 -7.4529948234558105
[INFO] find best focal: 1400
[INFO] coarse fitting...
2.6739368438720703 -7.729089260101318
[INFO] fitting light...
[INFO] fine frame-wise fitting...
0 of 293 done
1 of 293 done
2 of 293 done
3 of 293 done
4 of 293 done
5 of 293 done
6 of 293 done
7 of 293 done
8 of 293 done
9 of 293 done
10 of 293 done
11 of 293 done
12 of 293 done
13 of 293 done
14 of 293 done
15 of 293 done
16 of 293 done
17 of 293 done
18 of 293 done
19 of 293 done
20 of 293 done
21 of 293 done
22 of 293 done
23 of 293 done
24 of 293 done
25 of 293 done
26 of 293 done
27 of 293 done
28 of 293 done
29 of 293 done
30 of 293 done
31 of 293 done
32 of 293 done
33 of 293 done
34 of 293 done
35 of 293 done
36 of 293 done
37 of 293 done
38 of 293 done
39 of 293 done
40 of 293 done
41 of 293 done
42 of 293 done
43 of 293 done
44 of 293 done
45 of 293 done
46 of 293 done
47 of 293 done
48 of 293 done
49 of 293 done
50 of 293 done
51 of 293 done
52 of 293 done
53 of 293 done
54 of 293 done
55 of 293 done
56 of 293 done
57 of 293 done
58 of 293 done
59 of 293 done
60 of 293 done
61 of 293 done
62 of 293 done
63 of 293 done
64 of 293 done
65 of 293 done
66 of 293 done
67 of 293 done
68 of 293 done
69 of 293 done
70 of 293 done
71 of 293 done
72 of 293 done
73 of 293 done
74 of 293 done
75 of 293 done
76 of 293 done
77 of 293 done
78 of 293 done
79 of 293 done
80 of 293 done
81 of 293 done
82 of 293 done
83 of 293 done
84 of 293 done
85 of 293 done
86 of 293 done
87 of 293 done
88 of 293 done
89 of 293 done
90 of 293 done
91 of 293 done
92 of 293 done
93 of 293 done
94 of 293 done
95 of 293 done
96 of 293 done
97 of 293 done
98 of 293 done
99 of 293 done
100 of 293 done
101 of 293 done
102 of 293 done
103 of 293 done
104 of 293 done
105 of 293 done
106 of 293 done
107 of 293 done
108 of 293 done
109 of 293 done
110 of 293 done
111 of 293 done
112 of 293 done
113 of 293 done
114 of 293 done
115 of 293 done
116 of 293 done
117 of 293 done
118 of 293 done
119 of 293 done
120 of 293 done
121 of 293 done
122 of 293 done
123 of 293 done
124 of 293 done
125 of 293 done
126 of 293 done
127 of 293 done
128 of 293 done
129 of 293 done
130 of 293 done
131 of 293 done
132 of 293 done
133 of 293 done
134 of 293 done
135 of 293 done
136 of 293 done
137 of 293 done
138 of 293 done
139 of 293 done
140 of 293 done
141 of 293 done
142 of 293 done
143 of 293 done
144 of 293 done
145 of 293 done
146 of 293 done
147 of 293 done
148 of 293 done
149 of 293 done
150 of 293 done
151 of 293 done
152 of 293 done
153 of 293 done
154 of 293 done
155 of 293 done
156 of 293 done
157 of 293 done
158 of 293 done
159 of 293 done
160 of 293 done
161 of 293 done
162 of 293 done
163 of 293 done
164 of 293 done
165 of 293 done
166 of 293 done
167 of 293 done
168 of 293 done
169 of 293 done
170 of 293 done
171 of 293 done
172 of 293 done
173 of 293 done
174 of 293 done
175 of 293 done
176 of 293 done
177 of 293 done
178 of 293 done
179 of 293 done
180 of 293 done
181 of 293 done
182 of 293 done
183 of 293 done
184 of 293 done
185 of 293 done
186 of 293 done
187 of 293 done
188 of 293 done
189 of 293 done
190 of 293 done
191 of 293 done
192 of 293 done
193 of 293 done
194 of 293 done
195 of 293 done
196 of 293 done
197 of 293 done
198 of 293 done
199 of 293 done
200 of 293 done
201 of 293 done
202 of 293 done
203 of 293 done
204 of 293 done
205 of 293 done
206 of 293 done
207 of 293 done
208 of 293 done
209 of 293 done
210 of 293 done
211 of 293 done
212 of 293 done
213 of 293 done
214 of 293 done
215 of 293 done
216 of 293 done
217 of 293 done
218 of 293 done
219 of 293 done
220 of 293 done
221 of 293 done
222 of 293 done
223 of 293 done
224 of 293 done
225 of 293 done
226 of 293 done
227 of 293 done
228 of 293 done
229 of 293 done
230 of 293 done
231 of 293 done
232 of 293 done
233 of 293 done
234 of 293 done
235 of 293 done
236 of 293 done
237 of 293 done
238 of 293 done
239 of 293 done
240 of 293 done
241 of 293 done
242 of 293 done
243 of 293 done
244 of 293 done
245 of 293 done
246 of 293 done
247 of 293 done
248 of 293 done
249 of 293 done
250 of 293 done
251 of 293 done
252 of 293 done
253 of 293 done
254 of 293 done
255 of 293 done
256 of 293 done
257 of 293 done
258 of 293 done
259 of 293 done
260 of 293 done
261 of 293 done
262 of 293 done
263 of 293 done
264 of 293 done
265 of 293 done
266 of 293 done
267 of 293 done
268 of 293 done
269 of 293 done
270 of 293 done
271 of 293 done
272 of 293 done
273 of 293 done
274 of 293 done
275 of 293 done
276 of 293 done
277 of 293 done
278 of 293 done
279 of 293 done
280 of 293 done
281 of 293 done
282 of 293 done
283 of 293 done
284 of 293 done
285 of 293 done
286 of 293 done
287 of 293 done
288 of 293 done
289 of 293 done
290 of 293 done
291 of 293 done
292 of 293 done
params saved
[INFO] ===== finished face tracking =====
[INFO] ===== save transforms =====
[INFO] ===== finished saving transforms =====

**Comment by ZiqiaoPeng** [comment]
This is not SyncTalk's preprocessing code, please use SyncTalk's.
