### ISSUE TITLE
使用deepspeech模型，推理报错！~

### ISSUE THREAD

**Issue by wanghx1121** [ZiqiaoPeng/SyncTalk#95]
使用python main.py data/wf2 --workspace model/trial_wf2 -O --test --test_train --asr_model deepspeech --portrait --aud ./data/wf2/lzl.wav 命令推理，报错如下：
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/159092899/3cd53b80-ff2c-4afa-a929-4b02e2863cc0)

@ZiqiaoPeng 麻烦看一下！~谢谢

**Comment by StephanPan** [comment]
deepspeech的推理代码应该还有点问题，需要自行先把wav转成特征
![截屏2024-05-07 下午8 24 23](https://github.com/ZiqiaoPeng/SyncTalk/assets/37864281/1ac36ef0-eda9-4b1f-8380-e9d6bef964de)

**Comment by hasanshahid5678** [comment]
I am having some issue when I try to preprocess the data. It is giving the following tracebacks.
[INFO] ===== extract audio labels for data/apd/aud.wav =====
Traceback (most recent call last):
File "data_utils/deepspeech_features/extract_ds_features.py", line 10, in
from deepspeech_features import conv_audios_to_deepspeech
File "/home/europa/work/video_deep_fake/SyncTalk/data_utils/deepspeech_features/deepspeech_features.py", line 13, in
import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow.compat'

I have already installed the tensorflow using pip install tensorflow-gpu==2.8.1 and pulled the latest code.
After I ignored this error in preprocessing and started training using deepspeech, the following error occured.
[INFO] load 5094 train frames.
Traceback (most recent call last):
File "main.py", line 219, in
train_loader = NeRFDataset(opt, device=device, type='train').dataloader()
File "/home/europa/work/video_deep_fake/SyncTalk/nerf_triplane/provider.py", line 166, in init
aud_features = np.load(os.path.join(self.root_path, 'aud_ds.npy'))
File "/opt/conda/envs/synctalk/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/apd/aud_ds.npy'

**Comment by ZiqiaoPeng** [comment]
使用deepspeech模型需要使用npy进行推理，只有ave可以用wav进行推理。
