### ISSUE TITLE
预训练时，高频出现loss=nan问题

### ISSUE THREAD

**Issue by wanghx1121** [ZiqiaoPeng/SyncTalk#98]
使用python main.py data/wf3 --workspace model/trial_wf3 -O --iters 200000 --asr_model deepspeech训练时，高频率出现nan问题。
![image](https://github.com/ZiqiaoPeng/SyncTalk/assets/159092899/2b7f90e4-bcd0-4cc3-86d6-f337e74bf9f0)
@ZiqiaoPeng  请帮忙看一下，谢谢！~

**Comment by VincentHu19** [comment]
> 使用python main.py data/wf3 --workspace model/trial_wf3 -O --iters 200000 --asr_model deepspeech训练时，高频率出现nan问题。 ![image](https://private-user-images.githubusercontent.com/159092899/328749738-2b7f90e4-bcd0-4cc3-86d6-f337e74bf9f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTQzMDQsIm5iZiI6MTcxNTE1NDAwNCwicGF0aCI6Ii8xNTkwOTI4OTkvMzI4NzQ5NzM4LTJiN2Y5MGU0LWJjZDAtNGNjMy04NmQ2LWYzMzdlNzRiZjlmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwNzQwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmM4MGI3Yjk4N2ZjYzM0OTlkOGMwZGVjMmMxMjQ1MjVkMjczNzA1ZGJiYmM1YmQ4NjAwOWQ0ZDk3MmIxN2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bHCVKT5jJPtWIuIT5jKhurefH4cbk1A7v00df7g8z2k) @ZiqiaoPeng 请帮忙看一下，谢谢！~

请问你训练用的语音是英文还是中文，以及你用`--asr_model deepspeech`的选项训练，是否会出现loss=nan或者其他问题。

**Comment by wanghx1121** [comment]
> > 使用python main.py data/wf3 --workspace model/trial_wf3 -O --iters 200000 --asr_model deepspeech训练时，高频率出现nan问题。 ![image](https://private-user-images.githubusercontent.com/159092899/328749738-2b7f90e4-bcd0-4cc3-86d6-f337e74bf9f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTQzMDQsIm5iZiI6MTcxNTE1NDAwNCwicGF0aCI6Ii8xNTkwOTI4OTkvMzI4NzQ5NzM4LTJiN2Y5MGU0LWJjZDAtNGNjMy04NmQ2LWYzMzdlNzRiZjlmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwNzQwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmM4MGI3Yjk4N2ZjYzM0OTlkOGMwZGVjMmMxMjQ1MjVkMjczNzA1ZGJiYmM1YmQ4NjAwOWQ0ZDk3MmIxN2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bHCVKT5jJPtWIuIT5jKhurefH4cbk1A7v00df7g8z2k) @ZiqiaoPeng 请帮忙看一下，谢谢！~
> 
> 请问你训练用的语音是英文还是中文，以及你用`--asr_model ave`的选项训练，是否会出现loss=nan或者其他问题。

@VincentHu19 你好，我训练用的是中文。使用ave部署较大时，也会大概率出现！~

**Comment by ZiqiaoPeng** [comment]
最新的代码应该已经修复该问题，请再次尝试训练。
